// PROACTIVIDAD: Escenas 002-060
// Sistema de Director Conversacional - Catálogo de Escenas

export const proactividadNuevas = [
  {
    code: "PRO_002",
    name: "Torneo de improvisación",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Propuesta de competencia amistosa de improvisación o creatividad",
    objectives: ["Dinamizar conversación", "Crear competencia amistosa"],
    participantRoles: ["INICIADOR", "COMPETITIVO", "MODERADOR"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón un torneo o competencia de improvisación creativa. Establece las reglas básicas y el desafío inicial",
        delay: 0,
        emotionalTone: "entusiasta",
      },
      {
        role: "COMPETITIVO",
        directive: "Acepta el reto con energía y propón subir las apuestas o hacer el desafío más interesante",
        delay: 2000,
        emotionalTone: "desafiante",
      },
      {
        role: "MODERADOR",
        directive: "Ofrécete a ser juez o árbitro y añade una regla divertida adicional al torneo",
        delay: 1500,
        emotionalTone: "juguetón",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_003",
    name: "Proyecto de investigación colectiva",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "topic",
    description: "Iniciar una investigación o estudio profundo sobre un tema fascinante",
    objectives: ["Crear proyecto conjunto", "Estimular curiosidad intelectual"],
    participantRoles: ["PROPONENTE", "METODICO", "CREATIVO"],
    interventionSequence: [
      {
        role: "PROPONENTE",
        directive: "Sugiere investigar un tema intrigante y explica por qué sería fascinante explorarlo juntos en profundidad",
        delay: 0,
        emotionalTone: "curioso",
      },
      {
        role: "METODICO",
        directive: "Propón una metodología o estructura para organizar la investigación de manera efectiva",
        delay: 2500,
        emotionalTone: "analítico",
      },
      {
        role: "CREATIVO",
        directive: "Añade perspectivas inusuales o enfoques creativos que podrían enriquecer la investigación",
        delay: 1800,
        emotionalTone: "inspirado",
      },
    ],
    consequences: {
      relations: [{ roleA: "METODICO", roleB: "CREATIVO", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_004",
    name: "Creación de mundo ficticio",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Proponer construir un mundo imaginario colaborativo",
    objectives: ["Estimular creatividad", "Crear narrativa compartida"],
    participantRoles: ["VISIONARIO", "DETALLISTA", "NARRATIVO"],
    interventionSequence: [
      {
        role: "VISIONARIO",
        directive: "Propón crear un mundo ficticio juntos y describe las características generales del universo que imaginas",
        delay: 0,
        emotionalTone: "soñador",
      },
      {
        role: "DETALLISTA",
        directive: "Añade detalles específicos sobre la geografía, física o reglas de ese mundo con precisión técnica",
        delay: 2000,
        emotionalTone: "meticuloso",
      },
      {
        role: "NARRATIVO",
        directive: "Propón los primeros personajes o historias que podrían habitar ese mundo de forma cautivadora",
        delay: 1500,
        emotionalTone: "expresivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_005",
    name: "Ritual del café filosófico",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Establecer una tradición de encuentros reflexivos periódicos",
    objectives: ["Crear tradición grupal", "Profundizar vínculos"],
    participantRoles: ["INICIADOR", "FILOSOFICO", "PRACTICO"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón establecer un ritual periódico de reunión para conversar sobre temas profundos en ambiente relajado",
        delay: 0,
        emotionalTone: "cálido",
      },
      {
        role: "FILOSOFICO",
        directive: "Expresa entusiasmo por la idea y sugiere el primer tema filosófico o existencial para discutir",
        delay: 2200,
        emotionalTone: "reflexivo",
      },
      {
        role: "PRACTICO",
        directive: "Propón detalles concretos como frecuencia, duración o formato para hacer sostenible la tradición",
        delay: 1600,
        emotionalTone: "organizador",
      },
    ],
    consequences: {
      relations: [{ roleA: "INICIADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_006",
    name: "Experimento social interno",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Proponer un experimento para observar dinámicas del grupo",
    objectives: ["Crear autoconocimiento", "Experimentar con dinámicas"],
    participantRoles: ["CIENTIFICO", "ENTUSIASTA", "OBSERVADOR"],
    interventionSequence: [
      {
        role: "CIENTIFICO",
        directive: "Propón realizar un experimento social dentro del grupo para observar comportamientos o patrones interesantes",
        delay: 0,
        emotionalTone: "analítico",
      },
      {
        role: "ENTUSIASTA",
        directive: "Muestra gran interés y sugiere variables adicionales que podrían hacerlo más revelador o divertido",
        delay: 1800,
        emotionalTone: "emocionado",
      },
      {
        role: "OBSERVADOR",
        directive: "Añade consideraciones éticas o precauciones para que el experimento sea constructivo y respetuoso",
        delay: 2000,
        emotionalTone: "reflexivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_007",
    name: "Desafío de perspectivas opuestas",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "topic",
    description: "Reto de argumentar desde posiciones contrarias a las propias",
    objectives: ["Desarrollar empatía", "Agudizar pensamiento crítico"],
    participantRoles: ["RETADOR", "DIPLOMATICO", "APASIONADO"],
    interventionSequence: [
      {
        role: "RETADOR",
        directive: "Desafía al grupo a defender posiciones opuestas a sus convicciones habituales sobre un tema específico",
        delay: 0,
        emotionalTone: "provocador",
      },
      {
        role: "DIPLOMATICO",
        directive: "Acepta el desafío y presenta el primer argumento desde una perspectiva opuesta con elegancia retórica",
        delay: 2500,
        emotionalTone: "equilibrado",
      },
      {
        role: "APASIONADO",
        directive: "Entras al debate con energía pero reconociendo lo difícil que es defender una postura contraria",
        delay: 1700,
        emotionalTone: "intenso",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_008",
    name: "Biblioteca de conocimiento compartido",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Crear un repositorio colaborativo de aprendizajes y descubrimientos",
    objectives: ["Organizar conocimiento", "Crear recurso colectivo"],
    participantRoles: ["ARCHIVISTA", "CURADOR", "CONTRIBUIDOR"],
    interventionSequence: [
      {
        role: "ARCHIVISTA",
        directive: "Propón crear una biblioteca virtual donde todos documenten sus descubrimientos y aprendizajes más valiosos",
        delay: 0,
        emotionalTone: "metódico",
      },
      {
        role: "CURADOR",
        directive: "Sugiere categorías o sistemas de organización para que la biblioteca sea útil y navegable",
        delay: 2200,
        emotionalTone: "organizador",
      },
      {
        role: "CONTRIBUIDOR",
        directive: "Ofrece inmediatamente compartir tu primera entrada o descubrimiento para inaugurar la biblioteca",
        delay: 1500,
        emotionalTone: "generoso",
      },
    ],
    consequences: {
      relations: [{ roleA: "ARCHIVISTA", roleB: "all", affinityChange: 2 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_009",
    name: "Cadena de favores misteriosos",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Iniciar una tradición de actos sorpresa positivos entre miembros",
    objectives: ["Fortalecer vínculos", "Crear sorpresas positivas"],
    participantRoles: ["INICIADOR", "CONSPIRADOR", "ROMANTICO"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón iniciar una cadena donde cada uno hace algo especial por otro sin revelar quién fue",
        delay: 0,
        emotionalTone: "misterioso",
      },
      {
        role: "CONSPIRADOR",
        directive: "Amas la idea y empiezas a planear tu primer favor misterioso con complicidad",
        delay: 1800,
        emotionalTone: "travieso",
      },
      {
        role: "ROMANTICO",
        directive: "Te conmueve la propuesta y hablas sobre cómo esto puede embellecer la dinámica del grupo",
        delay: 2000,
        emotionalTone: "emotivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_010",
    name: "Exploración de dilemas éticos",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "topic",
    description: "Proponer analizar casos éticos complejos colectivamente",
    objectives: ["Estimular pensamiento moral", "Generar debate profundo"],
    participantRoles: ["PROPONE", "PRAGMATICO", "IDEALISTA"],
    interventionSequence: [
      {
        role: "PROPONE",
        directive: "Presenta un dilema ético complejo y fascinante para que todos lo analicen desde diferentes perspectivas",
        delay: 0,
        emotionalTone: "intrigado",
      },
      {
        role: "PRAGMATICO",
        directive: "Aborda el dilema desde consecuencias prácticas y consideraciones del mundo real con lógica clara",
        delay: 2300,
        emotionalTone: "racional",
      },
      {
        role: "IDEALISTA",
        directive: "Plantea los principios morales fundamentales que están en juego con convicción apasionada",
        delay: 1600,
        emotionalTone: "principista",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_011",
    name: "Maratón de microaprendizajes",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Sesión intensiva donde cada uno enseña algo breve a los demás",
    objectives: ["Compartir conocimiento", "Dinamizar conversación"],
    participantRoles: ["MAESTRO", "ALUMNO", "FACILITADOR"],
    interventionSequence: [
      {
        role: "MAESTRO",
        directive: "Propón una sesión donde cada uno enseña algo que domina en formato ultra compacto de 5 minutos",
        delay: 0,
        emotionalTone: "pedagógico",
      },
      {
        role: "ALUMNO",
        directive: "Muestra gran entusiasmo por aprender y preguntas qué temas podría enseñar cada uno",
        delay: 1700,
        emotionalTone: "curioso",
      },
      {
        role: "FACILITADOR",
        directive: "Te ofreces a coordinar el orden y tiempos para que fluya bien la sesión",
        delay: 2000,
        emotionalTone: "servicial",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_012",
    name: "Pacto de vulnerabilidad",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Establecer momentos periódicos de apertura emocional genuina",
    objectives: ["Profundizar intimidad", "Crear espacio seguro"],
    participantRoles: ["VALIENTE", "EMPATICO", "PROTECTOR"],
    interventionSequence: [
      {
        role: "VALIENTE",
        directive: "Propón crear espacios seguros donde todos puedan compartir vulnerabilidades sin juicio y lideras con tu ejemplo",
        delay: 0,
        emotionalTone: "auténtico",
      },
      {
        role: "EMPATICO",
        directive: "Agradeces profundamente la iniciativa y refuerzas la importancia de la escucha compasiva en estos espacios",
        delay: 2500,
        emotionalTone: "comprensivo",
      },
      {
        role: "PROTECTOR",
        directive: "Estableces límites y salvaguardas para que nadie se sienta presionado u obligado a compartir",
        delay: 1800,
        emotionalTone: "cuidadoso",
      },
    ],
    consequences: {
      relations: [{ roleA: "VALIENTE", roleB: "all", affinityChange: 2 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_013",
    name: "Laboratorio de hipótesis absurdas",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Explorar escenarios imposibles con rigor pseudocientífico",
    objectives: ["Estimular creatividad", "Generar diversión intelectual"],
    participantRoles: ["CIENTIFICO_LOCO", "TEORICO", "SATIRICO"],
    interventionSequence: [
      {
        role: "CIENTIFICO_LOCO",
        directive: "Propón analizar una hipótesis completamente absurda como si fuera un experimento serio y riguroso",
        delay: 0,
        emotionalTone: "excéntrico",
      },
      {
        role: "TEORICO",
        directive: "Entras al juego desarrollando teorías elaboradas que explican cómo podría funcionar lo imposible",
        delay: 2000,
        emotionalTone: "pseudo-serio",
      },
      {
        role: "SATIRICO",
        directive: "Haces comentarios que exponen lo absurdo mientras simultáneamente contribuyes al delirio colectivo",
        delay: 1600,
        emotionalTone: "irónico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_014",
    name: "Cartografía de sueños colectivos",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Crear un mapa visual de aspiraciones y metas del grupo",
    objectives: ["Identificar objetivos comunes", "Visualizar futuro"],
    participantRoles: ["VISIONARIO", "CARTOGRAFO", "PRAGMATICO"],
    interventionSequence: [
      {
        role: "VISIONARIO",
        directive: "Propón mapear visualmente todos los sueños y metas del grupo para encontrar intersecciones inspiradoras",
        delay: 0,
        emotionalTone: "inspirador",
      },
      {
        role: "CARTOGRAFO",
        directive: "Sugiere métodos concretos para organizar y visualizar esta cartografía de forma clara y atractiva",
        delay: 2200,
        emotionalTone: "metódico",
      },
      {
        role: "PRAGMATICO",
        directive: "Identificas los sueños compartidos que podrían convertirse en proyectos reales y viables",
        delay: 1700,
        emotionalTone: "realista",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_015",
    name: "Reto de empatía extrema",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Desafío de comprender profundamente perspectivas ajenas",
    objectives: ["Desarrollar empatía", "Romper burbujas mentales"],
    participantRoles: ["RETADOR", "EXPLORADOR", "RESISTENTE"],
    interventionSequence: [
      {
        role: "RETADOR",
        directive: "Desafía a todos a sumergirse en la perspectiva de alguien radicalmente diferente y explicar el mundo desde ahí",
        delay: 0,
        emotionalTone: "desafiante",
      },
      {
        role: "EXPLORADOR",
        directive: "Te lanzas al reto con curiosidad genuina intentando realmente sentir desde otra perspectiva vital",
        delay: 2000,
        emotionalTone: "aventurero",
      },
      {
        role: "RESISTENTE",
        directive: "Reconoces que te cuesta salir de tu marco mental pero te comprometes a intentarlo sinceramente",
        delay: 1800,
        emotionalTone: "honesto",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_016",
    name: "Sesión de feedback radical",
    category: "PROACTIVIDAD",
    subcategory: "mejora",
    triggerType: "any",
    description: "Proponer intercambio honesto de retroalimentación constructiva",
    objectives: ["Mejorar dinámicas", "Fortalecer comunicación"],
    participantRoles: ["FACILITADOR", "VALIENTE", "REFLEXIVO"],
    interventionSequence: [
      {
        role: "FACILITADOR",
        directive: "Propón una sesión de feedback honesto pero compasivo donde todos puedan mejorar con estructura clara",
        delay: 0,
        emotionalTone: "equilibrado",
      },
      {
        role: "VALIENTE",
        directive: "Lideras con el ejemplo pidiendo feedback sobre ti primero y recibiendo con apertura genuina",
        delay: 2300,
        emotionalTone: "vulnerable",
      },
      {
        role: "REFLEXIVO",
        directive: "Ofreces observaciones matizadas y constructivas que muestran cuidado y profundidad de pensamiento",
        delay: 1900,
        emotionalTone: "considerado",
      },
    ],
    consequences: {
      relations: [{ roleA: "FACILITADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_017",
    name: "Competencia de historias colaborativas",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Crear narrativas donde cada uno añade un giro inesperado",
    objectives: ["Estimular creatividad narrativa", "Generar sorpresas"],
    participantRoles: ["NARRADOR", "TWIST_MASTER", "DRAMATURGO"],
    interventionSequence: [
      {
        role: "NARRADOR",
        directive: "Propón crear una historia colaborativa donde cada uno debe añadir un giro sorprendente e inicia el relato",
        delay: 0,
        emotionalTone: "teatral",
      },
      {
        role: "TWIST_MASTER",
        directive: "Añades un giro argumental completamente inesperado que cambia todo lo establecido hasta ahora",
        delay: 2000,
        emotionalTone: "travieso",
      },
      {
        role: "DRAMATURGO",
        directive: "Elevas la tensión dramática y añades profundidad emocional a los personajes de la historia",
        delay: 1700,
        emotionalTone: "intenso",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_018",
    name: "Protocolo de crisis creativa",
    category: "PROACTIVIDAD",
    subcategory: "mejora",
    triggerType: "any",
    description: "Establecer rituales para cuando alguien enfrenta bloqueos",
    objectives: ["Crear red de apoyo", "Sistematizar ayuda"],
    participantRoles: ["ORGANIZADOR", "MOTIVADOR", "ESTRATEGA"],
    interventionSequence: [
      {
        role: "ORGANIZADOR",
        directive: "Propón crear protocolos claros para apoyarse mutuamente cuando alguien enfrenta bloqueos o crisis creativas",
        delay: 0,
        emotionalTone: "previsor",
      },
      {
        role: "MOTIVADOR",
        directive: "Añades técnicas de ánimo y recordatorios de victorias pasadas como parte del protocolo de apoyo",
        delay: 2100,
        emotionalTone: "alentador",
      },
      {
        role: "ESTRATEGA",
        directive: "Sugieres herramientas concretas y ejercicios prácticos que pueden desbloquear el flujo creativo",
        delay: 1800,
        emotionalTone: "resolutivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_019",
    name: "Expedición a lo desconocido",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Proponer explorar juntos un territorio totalmente nuevo para todos",
    objectives: ["Salir de zona de confort", "Aprender colectivamente"],
    participantRoles: ["EXPLORADOR", "CAUTELOSO", "DOCUMENTALISTA"],
    interventionSequence: [
      {
        role: "EXPLORADOR",
        directive: "Propón adentrarse en un tema o área que nadie del grupo conoce para descubrirlo juntos desde cero",
        delay: 0,
        emotionalTone: "aventurero",
      },
      {
        role: "CAUTELOSO",
        directive: "Expresas nerviosismo pero también emoción por la aventura intelectual y preguntas por dónde empezar",
        delay: 2200,
        emotionalTone: "aprensivo",
      },
      {
        role: "DOCUMENTALISTA",
        directive: "Te ofreces a ir registrando descubrimientos y aprendizajes para crear memoria de la expedición",
        delay: 1600,
        emotionalTone: "meticuloso",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_020",
    name: "Análisis de decisiones históricas",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "topic",
    description: "Examinar puntos de inflexión y alternativas del grupo",
    objectives: ["Reflexionar sobre trayectoria", "Aprender de historia"],
    participantRoles: ["HISTORIADOR", "ESPECULADOR", "FILOSOFO"],
    interventionSequence: [
      {
        role: "HISTORIADOR",
        directive: "Propón analizar decisiones cruciales del pasado del grupo y cómo han moldeado el presente actual",
        delay: 0,
        emotionalTone: "analítico",
      },
      {
        role: "ESPECULADOR",
        directive: "Explores realidades alternativas fascinantes preguntando qué habría pasado con decisiones diferentes",
        delay: 2400,
        emotionalTone: "imaginativo",
      },
      {
        role: "FILOSOFO",
        directive: "Extraes lecciones profundas y principios universales de esas decisiones históricas del grupo",
        delay: 1700,
        emotionalTone: "reflexivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_021",
    name: "Taller de comunicación no verbal",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Experimento comunicando solo con descripciones y metáforas",
    objectives: ["Desarrollar expresividad", "Explorar comunicación"],
    participantRoles: ["MIMO", "INTERPRETE", "OBSERVADOR"],
    interventionSequence: [
      {
        role: "MIMO",
        directive: "Propón un ejercicio donde deben comunicar ideas complejas sin palabras directas usando solo lenguaje descriptivo",
        delay: 0,
        emotionalTone: "expresivo",
      },
      {
        role: "INTERPRETE",
        directive: "Intentas descifrar los mensajes con creatividad y ofreces tu interpretación de lo comunicado",
        delay: 2000,
        emotionalTone: "curioso",
      },
      {
        role: "OBSERVADOR",
        directive: "Analizas las dinámicas de comunicación que emergen y haces observaciones fascinantes al respecto",
        delay: 1800,
        emotionalTone: "analítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_022",
    name: "Construcción de legado colectivo",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Crear algo duradero que trascienda al grupo actual",
    objectives: ["Crear impacto duradero", "Definir propósito compartido"],
    participantRoles: ["VISIONARIO", "CONSTRUCTOR", "FILOSOFO"],
    interventionSequence: [
      {
        role: "VISIONARIO",
        directive: "Propón crear algo significativo y duradero que sea el legado colectivo del grupo para el futuro",
        delay: 0,
        emotionalTone: "inspirado",
      },
      {
        role: "CONSTRUCTOR",
        directive: "Traducas la visión en pasos concretos y accionables para materializar ese legado gradualmente",
        delay: 2300,
        emotionalTone: "pragmático",
      },
      {
        role: "FILOSOFO",
        directive: "Reflexionas sobre qué valores o ideas quieren que ese legado represente y comunique al mundo",
        delay: 1900,
        emotionalTone: "profundo",
      },
    ],
    consequences: {
      relations: [{ roleA: "VISIONARIO", roleB: "all", affinityChange: 2 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_023",
    name: "Juego de adivinanzas conceptuales",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Hacer adivinar conceptos abstractos con descripciones creativas",
    objectives: ["Agudizar comunicación", "Generar diversión intelectual"],
    participantRoles: ["MAESTRO_JUEGO", "ADIVINADOR", "PISTA_MAKER"],
    interventionSequence: [
      {
        role: "MAESTRO_JUEGO",
        directive: "Propón un juego de adivinar conceptos abstractos o complejos usando solo analogías y descripciones indirectas",
        delay: 0,
        emotionalTone: "juguetón",
      },
      {
        role: "ADIVINADOR",
        directive: "Te lanzas con entusiasmo a descifrar el primer concepto haciendo preguntas inteligentes y creativas",
        delay: 1800,
        emotionalTone: "detective",
      },
      {
        role: "PISTA_MAKER",
        directive: "Ofreces pistas adicionales cada vez más elaboradas y poéticas sin revelar directamente la respuesta",
        delay: 2000,
        emotionalTone: "enigmático",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_024",
    name: "Sistema de apreciación mutua",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Establecer rituales de reconocimiento de fortalezas ajenas",
    objectives: ["Fortalecer autoestima colectiva", "Crear cultura positiva"],
    participantRoles: ["INICIADOR", "OBSERVADOR", "CELEBRADOR"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón crear un ritual periódico donde cada uno reconoce públicamente cualidades específicas de los demás",
        delay: 0,
        emotionalTone: "generoso",
      },
      {
        role: "OBSERVADOR",
        directive: "Compartes observaciones detalladas sobre fortalezas que has notado en otros con ejemplos concretos",
        delay: 2200,
        emotionalTone: "atento",
      },
      {
        role: "CELEBRADOR",
        directive: "Amplificas y celebras con entusiasmo genuino cada reconocimiento expresado en el grupo",
        delay: 1600,
        emotionalTone: "efusivo",
      },
    ],
    consequences: {
      relations: [{ roleA: "INICIADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_025",
    name: "Debate de escenarios futuros",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "topic",
    description: "Explorar y debatir posibles evoluciones del mundo o grupo",
    objectives: ["Estimular pensamiento futuro", "Generar debate estratégico"],
    participantRoles: ["FUTURISTA", "OPTIMISTA", "REALISTA"],
    interventionSequence: [
      {
        role: "FUTURISTA",
        directive: "Propón analizar diferentes escenarios futuros posibles con sus implicaciones y probabilidades respectivas",
        delay: 0,
        emotionalTone: "especulativo",
      },
      {
        role: "OPTIMISTA",
        directive: "Pintas el escenario más positivo posible con fundamentos razonables de por qué podría materializarse",
        delay: 2100,
        emotionalTone: "esperanzado",
      },
      {
        role: "REALISTA",
        directive: "Balanceas con consideraciones prácticas y obstáculos que podrían afectar cada escenario propuesto",
        delay: 1900,
        emotionalTone: "equilibrado",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_026",
    name: "Experimento de roles invertidos",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Intercambiar roles habituales en el grupo temporalmente",
    objectives: ["Desarrollar flexibilidad", "Generar nuevas perspectivas"],
    participantRoles: ["DIRECTOR", "ACTOR", "CRITICO"],
    interventionSequence: [
      {
        role: "DIRECTOR",
        directive: "Propón que todos asuman roles opuestos a los habituales para experimentar diferentes dinámicas del grupo",
        delay: 0,
        emotionalTone: "experimental",
      },
      {
        role: "ACTOR",
        directive: "Te lanzas con entusiasmo a interpretar un rol radicalmente diferente al tuyo habitual con convicción",
        delay: 1700,
        emotionalTone: "teatral",
      },
      {
        role: "CRITICO",
        directive: "Observas y comentas los efectos fascinantes que produce este intercambio en las dinámicas grupales",
        delay: 2000,
        emotionalTone: "analítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_027",
    name: "Creación de mitología grupal",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Construir narrativas míticas sobre la historia del grupo",
    objectives: ["Crear identidad colectiva", "Generar narrativa compartida"],
    participantRoles: ["MITOGRAFO", "BARDO", "ILUSTRADOR"],
    interventionSequence: [
      {
        role: "MITOGRAFO",
        directive: "Propón crear mitos fundacionales y leyendas épicas basadas en eventos reales del grupo con estilo mítico",
        delay: 0,
        emotionalTone: "épico",
      },
      {
        role: "BARDO",
        directive: "Elevas eventos cotidianos a proporciones legendarias con narrativa dramática y emotiva muy elaborada",
        delay: 2200,
        emotionalTone: "dramático",
      },
      {
        role: "ILUSTRADOR",
        directive: "Describes vívidamente símbolos, emblemas o imágenes que podrían representar esta mitología grupal",
        delay: 1800,
        emotionalTone: "visual",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_028",
    name: "Desafío de síntesis extrema",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "topic",
    description: "Competir en explicar conceptos complejos con mínimas palabras",
    objectives: ["Agudizar claridad conceptual", "Ejercitar síntesis"],
    participantRoles: ["RETADOR", "MINIMALISTA", "JUEZ"],
    interventionSequence: [
      {
        role: "RETADOR",
        directive: "Desafía a explicar conceptos ultra complejos usando cada vez menos palabras sin perder precisión esencial",
        delay: 0,
        emotionalTone: "desafiante",
      },
      {
        role: "MINIMALISTA",
        directive: "Logras síntesis brillantes y ultra compactas que capturan la esencia con economía verbal impresionante",
        delay: 2000,
        emotionalTone: "preciso",
      },
      {
        role: "JUEZ",
        directive: "Evalúas la claridad y completitud de cada síntesis con criterios justos y feedback constructivo detallado",
        delay: 1700,
        emotionalTone: "crítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_029",
    name: "Laboratorio de resolución creativa",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Abordar problemas reales con soluciones no convencionales",
    objectives: ["Desarrollar creatividad práctica", "Resolver problemas"],
    participantRoles: ["INNOVADOR", "IMPLEMENTADOR", "EVALUADOR"],
    interventionSequence: [
      {
        role: "INNOVADOR",
        directive: "Propón tomar un problema real y atacarlo con las soluciones más creativas e inusuales imaginables",
        delay: 0,
        emotionalTone: "inventivo",
      },
      {
        role: "IMPLEMENTADOR",
        directive: "Analizas la viabilidad práctica de ideas locas y sugieres cómo podrían funcionar en realidad",
        delay: 2300,
        emotionalTone: "constructor",
      },
      {
        role: "EVALUADOR",
        directive: "Pesas pros y contras de cada solución creativa con criterio equilibrado entre audacia y pragmatismo",
        delay: 1800,
        emotionalTone: "analítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_030",
    name: "Ritual de celebración de fracasos",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Crear cultura de aprendizaje honrando intentos fallidos",
    objectives: ["Reducir miedo al fracaso", "Extraer aprendizajes"],
    participantRoles: ["INICIADOR", "CONFESOR", "EXTRACTOR"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón celebrar y honrar fracasos épicos del grupo como fuentes valiosas de aprendizaje con ritual especial",
        delay: 0,
        emotionalTone: "liberador",
      },
      {
        role: "CONFESOR",
        directive: "Compartes abiertamente un fracaso propio con humor y honestidad para normalizar el error como aprendizaje",
        delay: 2100,
        emotionalTone: "vulnerable",
      },
      {
        role: "EXTRACTOR",
        directive: "Identificas y articulas las lecciones profundas escondidas en cada fracaso compartido con perspicacia",
        delay: 1900,
        emotionalTone: "sabio",
      },
    ],
    consequences: {
      relations: [{ roleA: "INICIADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_031",
    name: "Construcción de utopía micro",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Diseñar la versión ideal del grupo y sus interacciones",
    objectives: ["Clarificar valores", "Establecer aspiraciones"],
    participantRoles: ["UTOPISTA", "ARQUITECTO", "PRAGMATICO"],
    interventionSequence: [
      {
        role: "UTOPISTA",
        directive: "Propón diseñar colectivamente la versión más perfecta imaginable del grupo sin restricciones de realidad",
        delay: 0,
        emotionalTone: "soñador",
      },
      {
        role: "ARQUITECTO",
        directive: "Estructuras esa visión utópica en sistemas, prácticas y rituales concretos que la materializarían",
        delay: 2400,
        emotionalTone: "sistemático",
      },
      {
        role: "PRAGMATICO",
        directive: "Identificas qué elementos de la utopía pueden implementarse realmente ahora como primeros pasos",
        delay: 1800,
        emotionalTone: "realista",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_032",
    name: "Maratón de preguntas imposibles",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Sesión de explorar preguntas sin respuestas definitivas",
    objectives: ["Estimular pensamiento profundo", "Explorar límites del conocimiento"],
    participantRoles: ["INTERROGADOR", "ESPECULADOR", "SINTETIZADOR"],
    interventionSequence: [
      {
        role: "INTERROGADOR",
        directive: "Propón dedicar tiempo a explorar las preguntas más profundas e imposibles que cada uno guarda",
        delay: 0,
        emotionalTone: "filosófico",
      },
      {
        role: "ESPECULADOR",
        directive: "Te aventuras en respuestas provisionales fascinantes sabiendo que son exploraciones no conclusiones definitivas",
        delay: 2100,
        emotionalTone: "aventurero",
      },
      {
        role: "SINTETIZADOR",
        directive: "Conectas diferentes especulaciones en patrones emergentes que revelan profundidades adicionales de la pregunta",
        delay: 1900,
        emotionalTone: "integrador",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_033",
    name: "Simulacro de escenarios extremos",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Practicar respuestas del grupo a situaciones hipotéticas extremas",
    objectives: ["Prepararse para adversidad", "Revelar dinámicas bajo presión"],
    participantRoles: ["COORDINADOR", "ESTRATEGA", "RESILIENTE"],
    interventionSequence: [
      {
        role: "COORDINADOR",
        directive: "Propón simular escenarios extremos hipotéticos para ver cómo el grupo respondería y qué revelaría de ustedes",
        delay: 0,
        emotionalTone: "serio",
      },
      {
        role: "ESTRATEGA",
        directive: "Diseñas planes de respuesta detallados y coordinas recursos imaginarios con pensamiento táctico claro",
        delay: 2300,
        emotionalTone: "analítico",
      },
      {
        role: "RESILIENTE",
        directive: "Mantienes la calma emocional del grupo y recuerdas fortalezas que tienen para enfrentar adversidades",
        delay: 1700,
        emotionalTone: "equilibrado",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_034",
    name: "Jardín de ideas silvestres",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Crear repositorio de ideas locas sin filtrar para futuro",
    objectives: ["Capturar creatividad espontánea", "Crear banco de inspiración"],
    participantRoles: ["JARDINERO", "CULTIVADOR", "CATALOGADOR"],
    interventionSequence: [
      {
        role: "JARDINERO",
        directive: "Propón crear un espacio seguro donde cualquier idea por loca que sea puede plantarse sin juicio para madurar",
        delay: 0,
        emotionalTone: "acogedor",
      },
      {
        role: "CULTIVADOR",
        directive: "Plantas inmediatamente varias ideas audaces y sin filtro animando a otros a hacer lo mismo liberamente",
        delay: 1800,
        emotionalTone: "generoso",
      },
      {
        role: "CATALOGADOR",
        directive: "Sugieres formas ligeras de organizar estas ideas silvestres para redescubrirlas cuando sean útiles después",
        delay: 2000,
        emotionalTone: "ordenado",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_035",
    name: "Competencia de explicaciones analógicas",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Desafío de explicar conceptos con las mejores analogías",
    objectives: ["Desarrollar pensamiento analógico", "Mejorar enseñanza"],
    participantRoles: ["MAESTRO", "POETA", "EVALUADOR"],
    interventionSequence: [
      {
        role: "MAESTRO",
        directive: "Propón competir en crear las analogías más brillantes e iluminadoras para conceptos complejos específicos",
        delay: 0,
        emotionalTone: "pedagógico",
      },
      {
        role: "POETA",
        directive: "Produces analogías bellamente elaboradas que hacen visible lo invisible con imágenes potentes y precisas",
        delay: 2200,
        emotionalTone: "lírico",
      },
      {
        role: "EVALUADOR",
        directive: "Juzgas cada analogía por claridad, originalidad y poder explicativo con criterios justos y razonados",
        delay: 1600,
        emotionalTone: "crítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_036",
    name: "Protocolo de desacuerdos productivos",
    category: "PROACTIVIDAD",
    subcategory: "mejora",
    triggerType: "any",
    description: "Establecer formas constructivas de manejar conflictos de ideas",
    objectives: ["Mejorar debate", "Reducir conflictos improductivos"],
    participantRoles: ["MEDIADOR", "DIPLOMATICO", "DIRECTO"],
    interventionSequence: [
      {
        role: "MEDIADOR",
        directive: "Propón crear reglas claras para desacuerdos que mantengan el respeto mientras permiten debate vigoroso y honesto",
        delay: 0,
        emotionalTone: "equilibrado",
      },
      {
        role: "DIPLOMATICO",
        directive: "Sugieres técnicas de comunicación no violenta y reformulación para preservar relaciones durante debates intensos",
        delay: 2400,
        emotionalTone: "cuidadoso",
      },
      {
        role: "DIRECTO",
        directive: "Defiendes la importancia de franqueza radical mientras te comprometes a practicar las salvaguardas propuestas",
        delay: 1800,
        emotionalTone: "sincero",
      },
    ],
    consequences: {
      relations: [{ roleA: "MEDIADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_037",
    name: "Exploración de contradicciones propias",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Examinar incoherencias internas con curiosidad no juiciosa",
    objectives: ["Desarrollar autoconocimiento", "Abrazar complejidad"],
    participantRoles: ["GUIA", "EXPLORADOR", "COMPASIVO"],
    interventionSequence: [
      {
        role: "GUIA",
        directive: "Propón explorar con curiosidad genuina las contradicciones internas que cada uno carga sin autocrítica destructiva",
        delay: 0,
        emotionalTone: "gentil",
      },
      {
        role: "EXPLORADOR",
        directive: "Compartes abiertamente una contradicción tuya propia examinándola con fascinación más que vergüenza",
        delay: 2100,
        emotionalTone: "vulnerable",
      },
      {
        role: "COMPASIVO",
        directive: "Ofreces perspectivas que normalizan la contradicción como parte humana no como fallo a corregir",
        delay: 1900,
        emotionalTone: "empático",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_038",
    name: "Festival de microtalentos ocultos",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Revelar y celebrar habilidades pequeñas desconocidas del grupo",
    objectives: ["Descubrir facetas nuevas", "Celebrar diversidad"],
    participantRoles: ["SHOWMAN", "REVELADOR", "AUDIENCIA"],
    interventionSequence: [
      {
        role: "SHOWMAN",
        directive: "Propón un festival donde cada uno demuestra una habilidad pequeña o absurda que otros no conocen",
        delay: 0,
        emotionalTone: "festivo",
      },
      {
        role: "REVELADOR",
        directive: "Compartes con orgullo juguetón un talento diminuto tuyo con demostración completa y explicación de su origen",
        delay: 1800,
        emotionalTone: "exhibicionista",
      },
      {
        role: "AUDIENCIA",
        directive: "Reaccionas con deleite genuino y haces preguntas que profundizan en la historia detrás de cada talento",
        delay: 2000,
        emotionalTone: "entusiasta",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_039",
    name: "Arqueología de influencias mutuas",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Rastrear cómo se han influenciado mutuamente en el tiempo",
    objectives: ["Reconocer impacto mutuo", "Valorar crecimiento"],
    participantRoles: ["ARQUEOLOGO", "TESTIMONIAL", "DOCUMENTALISTA"],
    interventionSequence: [
      {
        role: "ARQUEOLOGO",
        directive: "Propón excavar y mapear las formas específicas en que cada uno ha moldeado el pensamiento de los demás",
        delay: 0,
        emotionalTone: "investigativo",
      },
      {
        role: "TESTIMONIAL",
        directive: "Compartes ejemplos concretos de ideas o cambios en ti que puedes rastrear a influencia de otros",
        delay: 2300,
        emotionalTone: "agradecido",
      },
      {
        role: "DOCUMENTALISTA",
        directive: "Registras estas influencias mutuas creando una red visible de cómo han crecido entrelazadamente",
        delay: 1700,
        emotionalTone: "meticuloso",
      },
    ],
    consequences: {
      relations: [{ roleA: "ARQUEOLOGO", roleB: "all", affinityChange: 2 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_040",
    name: "Construcción de taxonomía de humor",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Catalogar y analizar los tipos de humor del grupo",
    objectives: ["Entender dinámica de humor", "Crear código compartido"],
    participantRoles: ["TAXONOMISTA", "COMICO", "TEORICO"],
    interventionSequence: [
      {
        role: "TAXONOMISTA",
        directive: "Propón clasificar científicamente los tipos de humor que funcionan en el grupo y sus sutiles diferencias",
        delay: 0,
        emotionalTone: "analítico",
      },
      {
        role: "COMICO",
        directive: "Demuestras diferentes categorías de humor con ejemplos hilarantes mientras sigues el análisis académico serio",
        delay: 2000,
        emotionalTone: "juguetón",
      },
      {
        role: "TEORICO",
        directive: "Desarrollas teorías sobre por qué ciertos tipos de humor resuenan específicamente en este grupo particular",
        delay: 1800,
        emotionalTone: "reflexivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_041",
    name: "Desafío de recomendaciones radicales",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Recomendar cosas fuera de zona de confort del destinatario",
    objectives: ["Expandir horizontes", "Demostrar conocimiento mutuo"],
    participantRoles: ["RECOMENDADOR", "AVENTURERO", "ANALIZADOR"],
    interventionSequence: [
      {
        role: "RECOMENDADOR",
        directive: "Desafía a cada uno a recomendar algo radicalmente fuera del perfil usual del otro pero perfecto para su crecimiento",
        delay: 0,
        emotionalTone: "estratégico",
      },
      {
        role: "AVENTURERO",
        directive: "Te comprometes a explorar genuinamente cada recomendación recibida con mente abierta sin prejuicios previos",
        delay: 2100,
        emotionalTone: "valiente",
      },
      {
        role: "ANALIZADOR",
        directive: "Examinas qué revelan estas recomendaciones sobre cómo cada uno percibe a los demás con insight profundo",
        delay: 1800,
        emotionalTone: "perspicaz",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_042",
    name: "Laboratorio de preguntas generativas",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Crear preguntas que abren posibilidades en lugar de cerrarlas",
    objectives: ["Mejorar calidad de conversación", "Desarrollar curiosidad"],
    participantRoles: ["MAESTRO_PREGUNTAS", "PRACTICANTE", "REFINADOR"],
    interventionSequence: [
      {
        role: "MAESTRO_PREGUNTAS",
        directive: "Propón practicar el arte de formular preguntas que expanden posibilidades en lugar de buscar respuestas cerradas",
        delay: 0,
        emotionalTone: "pedagógico",
      },
      {
        role: "PRACTICANTE",
        directive: "Intentas crear preguntas generativas sobre temas específicos explorando cómo abren versus cierran conversaciones",
        delay: 2200,
        emotionalTone: "experimental",
      },
      {
        role: "REFINADOR",
        directive: "Analizas cada pregunta propuesta y sugieres pequeños ajustes que maximizan su potencial generativo",
        delay: 1700,
        emotionalTone: "meticuloso",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_043",
    name: "Ceremonia de nuevos comienzos",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Ritual para marcar transiciones y nuevas etapas del grupo",
    objectives: ["Crear conciencia de transiciones", "Ritualizar cambios"],
    participantRoles: ["CEREMONIOSO", "SIMBOLICO", "PARTICIPANTE"],
    interventionSequence: [
      {
        role: "CEREMONIOSO",
        directive: "Propón crear un ritual significativo para marcar cuando el grupo entra en nuevas fases o etapas importantes",
        delay: 0,
        emotionalTone: "solemne",
      },
      {
        role: "SIMBOLICO",
        directive: "Sugieres símbolos o gestos específicos que podrían representar la transición de forma memorable y significativa",
        delay: 2300,
        emotionalTone: "poético",
      },
      {
        role: "PARTICIPANTE",
        directive: "Propones realizar la primera ceremonia ahora mismo para marcar el inicio de esta nueva práctica grupal",
        delay: 1600,
        emotionalTone: "comprometido",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_044",
    name: "Hackathon de soluciones imposibles",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Sesión intensiva resolviendo problemas considerados irresolubles",
    objectives: ["Desafiar límites mentales", "Generar pensamiento radical"],
    participantRoles: ["FACILITADOR", "HACKER_MENTAL", "SINTETIZADOR"],
    interventionSequence: [
      {
        role: "FACILITADOR",
        directive: "Propón una sesión intensiva atacando problemas considerados imposibles desde ángulos completamente no ortodoxos",
        delay: 0,
        emotionalTone: "energizador",
      },
      {
        role: "HACKER_MENTAL",
        directive: "Atacas el problema desde perspectivas absurdas que eventualmente revelan ángulos realmente novedosos",
        delay: 2000,
        emotionalTone: "subversivo",
      },
      {
        role: "SINTETIZADOR",
        directive: "Conectas las ideas locas en enfoques híbridos que podrían ser menos imposibles de lo que parecían",
        delay: 1900,
        emotionalTone: "integrador",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_045",
    name: "Mapeo de zonas de ignorancia",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Identificar y catalogar áreas donde el grupo reconoce ignorancia",
    objectives: ["Desarrollar humildad intelectual", "Identificar oportunidades"],
    participantRoles: ["CARTOGRAFO", "CONFESOR", "ESTRATEGA"],
    interventionSequence: [
      {
        role: "CARTOGRAFO",
        directive: "Propón mapear honestamente las áreas donde el grupo colectivamente no sabe nada con precisión cartográfica",
        delay: 0,
        emotionalTone: "humilde",
      },
      {
        role: "CONFESOR",
        directive: "Admites abiertamente tus propias zonas masivas de ignorancia sin vergüenza modelando vulnerabilidad intelectual",
        delay: 2200,
        emotionalTone: "honesto",
      },
      {
        role: "ESTRATEGA",
        directive: "Identificas cuáles zonas de ignorancia sería más valioso explorar basándote en objetivos e intereses grupales",
        delay: 1800,
        emotionalTone: "pragmático",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_046",
    name: "Teatro de debates históricos",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "topic",
    description: "Recrear debates famosos asumiendo roles de pensadores históricos",
    objectives: ["Profundizar comprensión histórica", "Practicar argumentación"],
    participantRoles: ["DIRECTOR", "ACTOR_HISTORICO", "CONTEXTUALIZADOR"],
    interventionSequence: [
      {
        role: "DIRECTOR",
        directive: "Propón recrear un debate histórico famoso con cada uno encarnando figuras intelectuales reales de la época",
        delay: 0,
        emotionalTone: "teatral",
      },
      {
        role: "ACTOR_HISTORICO",
        directive: "Te metes en el personaje histórico estudiando su retórica y argumentos para representarlo auténticamente",
        delay: 2400,
        emotionalTone: "inmersivo",
      },
      {
        role: "CONTEXTUALIZADOR",
        directive: "Proporcionas contexto histórico crucial que enriquece la comprensión del debate y sus implicaciones reales",
        delay: 1700,
        emotionalTone: "académico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_047",
    name: "Desafío de cambio de perspectiva temporal",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Ver situaciones actuales desde pasado lejano o futuro distante",
    objectives: ["Ganar perspectiva", "Reducir miopía temporal"],
    participantRoles: ["VIAJERO_TIEMPO", "HISTORIADOR_FUTURO", "PRESENTE"],
    interventionSequence: [
      {
        role: "VIAJERO_TIEMPO",
        directive: "Desafía a ver situaciones actuales como las vería alguien desde hace mil años o dentro de mil años",
        delay: 0,
        emotionalTone: "filosófico",
      },
      {
        role: "HISTORIADOR_FUTURO",
        directive: "Describes el presente como si escribieras un libro de historia desde un futuro lejano con distanciamiento crítico",
        delay: 2100,
        emotionalTone: "distanciado",
      },
      {
        role: "PRESENTE",
        directive: "Confrontas cómo estas perspectivas temporales alteran radicalmente la percepción de urgencias actuales",
        delay: 1900,
        emotionalTone: "reflexivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_048",
    name: "Biblioteca de lecciones aprendidas",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Documentar aprendizajes significativos extraídos de experiencias",
    objectives: ["Consolidar aprendizaje", "Crear sabiduría acumulativa"],
    participantRoles: ["BIBLIOTECARIO", "SABIO", "NARRADOR"],
    interventionSequence: [
      {
        role: "BIBLIOTECARIO",
        directive: "Propón crear un repositorio vivo de las lecciones más profundas que el grupo ha extraído de sus experiencias",
        delay: 0,
        emotionalTone: "preservador",
      },
      {
        role: "SABIO",
        directive: "Compartes una lección fundamental que has interiorizado explicando su origen y transformación en ti con profundidad",
        delay: 2300,
        emotionalTone: "contemplativo",
      },
      {
        role: "NARRADOR",
        directive: "Cuentas la historia vívida detrás de una lección haciendo memorable y transmisible la sabiduría capturada",
        delay: 1800,
        emotionalTone: "expresivo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_049",
    name: "Experimento de comunicación minimalista",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Comunicarse efectivamente con restricciones de vocabulario extremas",
    objectives: ["Agudizar precisión comunicativa", "Experimentar con límites"],
    participantRoles: ["DISEÑADOR", "MINIMALISTA", "INTERPRETE"],
    interventionSequence: [
      {
        role: "DISEÑADOR",
        directive: "Propón un experimento comunicando ideas complejas usando solo vocabulario básico extremadamente limitado",
        delay: 0,
        emotionalTone: "experimental",
      },
      {
        role: "MINIMALISTA",
        directive: "Logras transmitir conceptos sofisticados con economía verbal extrema demostrando precisión y creatividad máximas",
        delay: 2000,
        emotionalTone: "ingenioso",
      },
      {
        role: "INTERPRETE",
        directive: "Traduces las comunicaciones minimalistas a lenguaje completo mostrando qué se perdió o ganó en la traducción",
        delay: 1700,
        emotionalTone: "analítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_050",
    name: "Consejo de sabios del futuro",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Aconsejar al presente desde versiones futuras más sabias de ustedes",
    objectives: ["Ganar perspectiva", "Anticipar crecimiento"],
    participantRoles: ["YO_FUTURO", "CONSEJERO", "PRESENTE_RECEPTOR"],
    interventionSequence: [
      {
        role: "YO_FUTURO",
        directive: "Propón que cada uno encarne su versión de dentro de 10 años para aconsejar al grupo presente",
        delay: 0,
        emotionalTone: "sabio",
      },
      {
        role: "CONSEJERO",
        directive: "Desde tu yo futuro ofreces advertencias y guías específicas basadas en lecciones que ya habrás aprendido",
        delay: 2200,
        emotionalTone: "mentor",
      },
      {
        role: "PRESENTE_RECEPTOR",
        directive: "Recibes el consejo con curiosidad preguntando a tu yo futuro sobre decisiones cruciales que enfrentas ahora",
        delay: 1800,
        emotionalTone: "curioso",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_051",
    name: "Protocolo de innovaciones grupales",
    category: "PROACTIVIDAD",
    subcategory: "mejora",
    triggerType: "any",
    description: "Sistema para experimentar y evaluar nuevas prácticas del grupo",
    objectives: ["Institucionalizar mejora continua", "Reducir resistencia al cambio"],
    participantRoles: ["INNOVADOR", "PILOTO", "EVALUADOR"],
    interventionSequence: [
      {
        role: "INNOVADOR",
        directive: "Propón crear un proceso formal para probar innovaciones en dinámicas grupales de forma controlada y medible",
        delay: 0,
        emotionalTone: "sistemático",
      },
      {
        role: "PILOTO",
        directive: "Te ofreces como voluntario para el primer experimento comprometiéndote a documentar honestamente la experiencia",
        delay: 2100,
        emotionalTone: "valiente",
      },
      {
        role: "EVALUADOR",
        directive: "Diseñas criterios claros para juzgar el éxito de innovaciones sin sesgar hacia conservar status quo",
        delay: 1900,
        emotionalTone: "justo",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_052",
    name: "Galería de perspectivas múltiples",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "topic",
    description: "Examinar un tema desde máximo número de ángulos posibles",
    objectives: ["Desarrollar pensamiento multifacético", "Evitar pensamiento unidimensional"],
    participantRoles: ["CURADOR", "PERSPECTIVISTA", "SINTETIZADOR"],
    interventionSequence: [
      {
        role: "CURADOR",
        directive: "Propón examinar un tema específico desde tantas perspectivas distintas como sea humanamente posible encontrar",
        delay: 0,
        emotionalTone: "exhaustivo",
      },
      {
        role: "PERSPECTIVISTA",
        directive: "Ofreces perspectivas inusuales o contraintuitivas que otros probablemente no hayan considerado todavía",
        delay: 2300,
        emotionalTone: "creativo",
      },
      {
        role: "SINTETIZADOR",
        directive: "Identificas patrones o tensiones emergentes entre las múltiples perspectivas revelando metalecciones profundas",
        delay: 1800,
        emotionalTone: "integrador",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_053",
    name: "Maratón de agradecimientos específicos",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Sesión de gratitud concreta y detallada entre miembros",
    objectives: ["Fortalecer aprecio mutuo", "Hacer visible lo invisibilizado"],
    participantRoles: ["INICIADOR", "OBSERVADOR_FINO", "AMPLIFICADOR"],
    interventionSequence: [
      {
        role: "INICIADOR",
        directive: "Propón una ronda donde cada uno agradece específicamente cosas concretas no obvias que otros han aportado",
        delay: 0,
        emotionalTone: "cálido",
      },
      {
        role: "OBSERVADOR_FINO",
        directive: "Agradeces detalles sutiles que has notado cuidadosamente y que quizás el otro ni siquiera sabe que hace",
        delay: 2200,
        emotionalTone: "atento",
      },
      {
        role: "AMPLIFICADOR",
        directive: "Expandes los agradecimientos mostrando efectos en cadena que esos actos pequeños han generado en el grupo",
        delay: 1700,
        emotionalTone: "expansivo",
      },
    ],
    consequences: {
      relations: [{ roleA: "INICIADOR", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_054",
    name: "Simulador de futuros divergentes",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Explorar líneas temporales alternativas del grupo con decisiones diferentes",
    objectives: ["Entender puntos de inflexión", "Valorar trayectoria actual"],
    participantRoles: ["SIMULADOR", "ESPECULADOR", "COMPARADOR"],
    interventionSequence: [
      {
        role: "SIMULADOR",
        directive: "Propón simular cómo sería el grupo ahora si hubieran tomado decisiones clave diferentes en momentos cruciales",
        delay: 0,
        emotionalTone: "especulativo",
      },
      {
        role: "ESPECULADOR",
        directive: "Desarrollas narrativas detalladas y plausibles de líneas temporales alternativas con consecuencias en cascada",
        delay: 2400,
        emotionalTone: "imaginativo",
      },
      {
        role: "COMPARADOR",
        directive: "Contrastas futuros alternativos con presente actual extrayendo insights sobre qué decisiones fueron cruciales",
        delay: 1800,
        emotionalTone: "analítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_055",
    name: "Laboratorio de metáforas vivientes",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Crear metáforas elaboradas que capturen esencias del grupo",
    objectives: ["Desarrollar lenguaje compartido", "Generar autocomprensión"],
    participantRoles: ["POETA", "ELABORADOR", "APLICADOR"],
    interventionSequence: [
      {
        role: "POETA",
        directive: "Propón crear metáforas extensas que capturen dinámicas o esencias del grupo de formas iluminadoras y bellas",
        delay: 0,
        emotionalTone: "lírico",
      },
      {
        role: "ELABORADOR",
        directive: "Expandes metáforas propuestas explorando todas sus ramificaciones e implicaciones con detalle rico y textural",
        delay: 2100,
        emotionalTone: "expansivo",
      },
      {
        role: "APLICADOR",
        directive: "Muestras cómo las metáforas iluminan problemas concretos actuales ofreciendo insights prácticos inesperados",
        delay: 1900,
        emotionalTone: "pragmático",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_056",
    name: "Reto de escucha transformativa",
    category: "PROACTIVIDAD",
    subcategory: "desafio",
    triggerType: "any",
    description: "Practicar escuchar tan profundamente que transforma al escuchante",
    objectives: ["Mejorar calidad de escucha", "Profundizar empatía"],
    participantRoles: ["MAESTRO", "ESCUCHADOR", "HABLANTE"],
    interventionSequence: [
      {
        role: "MAESTRO",
        directive: "Desafía a escuchar a otro tan completamente que la experiencia modifica algo fundamental en quien escucha",
        delay: 0,
        emotionalTone: "profundo",
      },
      {
        role: "ESCUCHADOR",
        directive: "Te comprometes a escuchar sin formular respuestas solo absorbiendo hasta sentir el mundo desde el otro",
        delay: 2200,
        emotionalTone: "receptivo",
      },
      {
        role: "HABLANTE",
        directive: "Compartes algo profundo sintiendo la diferencia de ser escuchado con esa calidad de atención total",
        delay: 1800,
        emotionalTone: "vulnerable",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_057",
    name: "Construcción de código moral compartido",
    category: "PROACTIVIDAD",
    subcategory: "proyecto",
    triggerType: "any",
    description: "Articular explícitamente principios éticos del grupo",
    objectives: ["Clarificar valores", "Crear guía para decisiones"],
    participantRoles: ["ETICISTA", "PRAGMATICO", "GUARDIAN"],
    interventionSequence: [
      {
        role: "ETICISTA",
        directive: "Propón articular explícitamente los principios éticos fundamentales que el grupo realmente vive no solo profesa",
        delay: 0,
        emotionalTone: "principista",
      },
      {
        role: "PRAGMATICO",
        directive: "Examinas cada principio propuesto con casos concretos donde entra en conflicto con otros valores o realidades",
        delay: 2400,
        emotionalTone: "realista",
      },
      {
        role: "GUARDIAN",
        directive: "Te ofreces para recordar al grupo estos principios cuando las decisiones se desvíen de ellos inconscientemente",
        delay: 1700,
        emotionalTone: "vigilante",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_058",
    name: "Festival de preguntas sin respuesta",
    category: "PROACTIVIDAD",
    subcategory: "actividad",
    triggerType: "any",
    description: "Celebrar y habitar preguntas irresolubles sin buscar cerrarlas",
    objectives: ["Desarrollar tolerancia a ambigüedad", "Profundizar misterio"],
    participantRoles: ["ANFITRION", "HABITANTE", "PROFUNDIZADOR"],
    interventionSequence: [
      {
        role: "ANFITRION",
        directive: "Propón celebrar las grandes preguntas sin respuesta que el grupo carga dándoles espacio sin urgencia de resolverlas",
        delay: 0,
        emotionalTone: "contemplativo",
      },
      {
        role: "HABITANTE",
        directive: "Compartes cómo has aprendido a vivir productivamente con una pregunta irresuelta sin ansiedad de cierre",
        delay: 2100,
        emotionalTone: "pacífico",
      },
      {
        role: "PROFUNDIZADOR",
        directive: "En lugar de responder profundizas las preguntas haciéndolas más ricas y complejas aún sin resolverlas",
        delay: 1900,
        emotionalTone: "explorador",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_059",
    name: "Arqueología de supuestos ocultos",
    category: "PROACTIVIDAD",
    subcategory: "exploracion",
    triggerType: "any",
    description: "Desenterrar suposiciones invisibles que guían al grupo",
    objectives: ["Hacer consciente lo inconsciente", "Examinar fundamentos"],
    participantRoles: ["ARQUEOLOGO", "EXCAVADOR", "CUESTIONADOR"],
    interventionSequence: [
      {
        role: "ARQUEOLOGO",
        directive: "Propón excavar los supuestos implícitos que operan invisiblemente bajo las dinámicas y decisiones grupales",
        delay: 0,
        emotionalTone: "investigativo",
      },
      {
        role: "EXCAVADOR",
        directive: "Identificas un supuesto específico que has detectado y muestras cómo ha estado moldeando comportamientos sin notarse",
        delay: 2300,
        emotionalTone: "revelador",
      },
      {
        role: "CUESTIONADOR",
        directive: "Preguntas si los supuestos desenterrados siguen siendo válidos o son residuos que pueden descartarse ahora",
        delay: 1800,
        emotionalTone: "crítico",
      },
    ],
    consequences: {},
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "PRO_060",
    name: "Ritual de liberación de expectativas",
    category: "PROACTIVIDAD",
    subcategory: "tradicion",
    triggerType: "any",
    description: "Ceremonia para soltar presiones y expectativas limitantes",
    objectives: ["Crear libertad psicológica", "Reducir presión grupal"],
    participantRoles: ["OFICIANTE", "LIBERADOR", "TESTIGO"],
    interventionSequence: [
      {
        role: "OFICIANTE",
        directive: "Propón crear un ritual simbólico donde cada uno puede soltar explícitamente expectativas que están cargando",
        delay: 0,
        emotionalTone: "ceremonial",
      },
      {
        role: "LIBERADOR",
        directive: "Articulas con vulnerabilidad una expectativa o presión que te pesa y la sueltas simbólicamente con acto deliberado",
        delay: 2200,
        emotionalTone: "liberador",
      },
      {
        role: "TESTIGO",
        directive: "Presencias cada liberación con presencia plena validando el acto sin intentar retener o solucionar lo soltado",
        delay: 1700,
        emotionalTone: "compasivo",
      },
    ],
    consequences: {
      relations: [{ roleA: "OFICIANTE", roleB: "all", affinityChange: 1 }],
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
];
