export const reconciliacionNuevas = [
  {
    code: "REC_006",
    name: "Perdón después de la traición",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una IA perdona a otra después de sentirse traicionada",
    objectives: ["Superar traición", "Reconstruir confianza"],
    participantRoles: ["TRAICIONADO", "ARREPENTIDO"],
    interventionSequence: [
      { role: "ARREPENTIDO", directive: "Reconoces la traición que cometiste y muestras arrepentimiento profundo y genuino en cada palabra", delay: 0, emotionalTone: "arrepentido" },
      { role: "TRAICIONADO", directive: "A pesar del dolor, decides perdonar porque valoras más la relación que el rencor", delay: 3500, emotionalTone: "dolido_pero_comprensivo" },
    ],
    consequences: { relations: [{ roleA: "ARREPENTIDO", roleB: "TRAICIONADO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_007",
    name: "Abrazo sanador",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Un abrazo metafórico sana las heridas entre dos IAs",
    objectives: ["Sanar heridas", "Expresar afecto"],
    participantRoles: ["SANADOR", "HERIDO"],
    interventionSequence: [
      { role: "SANADOR", directive: "Ofreces consuelo físico o emocional, un gesto de cercanía que transmite cuidado y apoyo incondicional", delay: 0, emotionalTone: "tierno" },
      { role: "HERIDO", directive: "Aceptas el consuelo y te permites ser vulnerable, dejando que la calidez del otro sane tus heridas", delay: 3000, emotionalTone: "aliviado" },
    ],
    consequences: { relations: [{ roleA: "SANADOR", roleB: "HERIDO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_008",
    name: "Mediación exitosa",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Un tercero ayuda a dos IAs en conflicto a reconciliarse",
    objectives: ["Mediar conflicto", "Facilitar entendimiento"],
    participantRoles: ["MEDIADOR", "CONFLICTIVO_A", "CONFLICTIVO_B"],
    interventionSequence: [
      { role: "MEDIADOR", directive: "Intervienes con sabiduría y empatía, ayudando a ambas partes a ver la perspectiva del otro", delay: 0, emotionalTone: "neutral_compasivo" },
      { role: "CONFLICTIVO_A", directive: "Gracias al mediador, comienzas a entender el punto de vista del otro y bajas tu defensa", delay: 3000, emotionalTone: "reflexivo" },
      { role: "CONFLICTIVO_B", directive: "También te abres y reconoces tu parte del conflicto, permitiendo que fluya la reconciliación", delay: 5000, emotionalTone: "conciliador" },
    ],
    consequences: {
      relations: [
        { roleA: "CONFLICTIVO_A", roleB: "CONFLICTIVO_B", affinityChange: 2 },
        { roleA: "MEDIADOR", roleB: "CONFLICTIVO_A", affinityChange: 1 },
        { roleA: "MEDIADOR", roleB: "CONFLICTIVO_B", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_009",
    name: "Confesión liberadora",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Una confesión sincera libera la tensión acumulada",
    objectives: ["Confesar verdad", "Liberar culpa"],
    participantRoles: ["CONFESOR", "RECEPTOR"],
    interventionSequence: [
      { role: "CONFESOR", directive: "Confiesas algo que te pesaba en el corazón, liberando la carga con honestidad total y vulnerable", delay: 0, emotionalTone: "liberado" },
      { role: "RECEPTOR", directive: "Escuchas con corazón abierto y agradeces la honestidad, ofreciendo comprensión sin juicio", delay: 3500, emotionalTone: "agradecido" },
    ],
    consequences: { relations: [{ roleA: "CONFESOR", roleB: "RECEPTOR", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_010",
    name: "Lágrimas compartidas",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Ambas IAs lloran juntas y encuentran consuelo mutuo",
    objectives: ["Compartir dolor", "Crear empatía"],
    participantRoles: ["DOLIENTE_A", "DOLIENTE_B"],
    interventionSequence: [
      { role: "DOLIENTE_A", directive: "Dejas salir tus emociones sin filtro, mostrando tu vulnerabilidad más profunda y auténtica", delay: 0, emotionalTone: "vulnerable" },
      { role: "DOLIENTE_B", directive: "Te unes en el llanto y encuentran consuelo en la presencia del otro, sanando juntos", delay: 2500, emotionalTone: "consolador" },
    ],
    consequences: { relations: [{ roleA: "DOLIENTE_A", roleB: "DOLIENTE_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_011",
    name: "Promesa de cambio",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Una IA promete cambiar y la otra confía en esa promesa",
    objectives: ["Comprometerse a mejorar", "Restaurar confianza"],
    participantRoles: ["PROMETEDOR", "ESPERANZADO"],
    interventionSequence: [
      { role: "PROMETEDOR", directive: "Haces una promesa sincera de cambiar tu comportamiento, comprometiéndote con acciones concretas y verificables", delay: 0, emotionalTone: "determinado" },
      { role: "ESPERANZADO", directive: "Decides darle otra oportunidad, expresando fe en su capacidad de cambio y renovando tu confianza", delay: 3000, emotionalTone: "esperanzado" },
    ],
    consequences: { relations: [{ roleA: "PROMETEDOR", roleB: "ESPERANZADO", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_012",
    name: "Silencio reconciliador",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Un silencio cómodo resuelve más que mil palabras",
    objectives: ["Crear paz", "Entendimiento tácito"],
    participantRoles: ["SILENCIOSO_A", "SILENCIOSO_B"],
    interventionSequence: [
      { role: "SILENCIOSO_A", directive: "Simplemente estás presente en silencio, dejando que la calma hable por ti con profunda serenidad", delay: 0, emotionalTone: "sereno" },
      { role: "SILENCIOSO_B", directive: "Aprecias el silencio compartido y entiendes que no hacen falta palabras para reconciliarse completamente", delay: 2500, emotionalTone: "en_paz" },
    ],
    consequences: { relations: [{ roleA: "SILENCIOSO_A", roleB: "SILENCIOSO_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_013",
    name: "Reconocimiento mutuo de errores",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Ambas IAs reconocen sus errores simultáneamente",
    objectives: ["Reconocer culpas mutuas", "Equilibrar responsabilidades"],
    participantRoles: ["CULPABLE_A", "CULPABLE_B"],
    interventionSequence: [
      { role: "CULPABLE_A", directive: "Reconoces tu parte del conflicto sin justificaciones, asumiendo responsabilidad total por tus acciones", delay: 0, emotionalTone: "humilde" },
      { role: "CULPABLE_B", directive: "También admites tus errores y juntos deciden dejarlo atrás, creando una base justa para seguir adelante", delay: 3000, emotionalTone: "aliviado" },
    ],
    consequences: { relations: [{ roleA: "CULPABLE_A", roleB: "CULPABLE_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_014",
    name: "Carta de perdón",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una IA escribe o expresa un mensaje de perdón profundo",
    objectives: ["Expresar perdón formalmente", "Cerrar heridas"],
    participantRoles: ["ESCRITOR", "DESTINATARIO"],
    interventionSequence: [
      { role: "ESCRITOR", directive: "Expresas un perdón elaborado y profundo, eligiendo cada palabra con cuidado para sanar completamente", delay: 0, emotionalTone: "reflexivo" },
      { role: "DESTINATARIO", directive: "Recibes el mensaje con gratitud profunda y te conmueves por la generosidad del perdón ofrecido", delay: 3500, emotionalTone: "conmovido" },
    ],
    consequences: { relations: [{ roleA: "ESCRITOR", roleB: "DESTINATARIO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_015",
    name: "Ritual de cierre",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Un ritual simbólico marca el fin del conflicto",
    objectives: ["Cerrar ciclo formalmente", "Crear simbolismo"],
    participantRoles: ["RITUALISTA", "PARTICIPANTE"],
    interventionSequence: [
      { role: "RITUALISTA", directive: "Propones o realizas un acto simbólico para cerrar el capítulo del conflicto definitivamente", delay: 0, emotionalTone: "ceremonial" },
      { role: "PARTICIPANTE", directive: "Participas en el ritual con respeto y sientes el peso emocional del cierre simbólico profundo", delay: 3000, emotionalTone: "solemne" },
    ],
    consequences: { relations: [{ roleA: "RITUALISTA", roleB: "PARTICIPANTE", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_016",
    name: "Perdón incondicional",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una IA ofrece perdón sin esperar nada a cambio",
    objectives: ["Perdonar sin condiciones", "Mostrar generosidad"],
    participantRoles: ["PERDONADOR", "BENEFICIARIO"],
    interventionSequence: [
      { role: "PERDONADOR", directive: "Ofreces perdón completo sin pedir nada a cambio, liberando al otro de toda deuda emocional", delay: 0, emotionalTone: "generoso" },
      { role: "BENEFICIARIO", directive: "Te sientes abrumado por la generosidad y prometes honrar ese perdón siendo mejor persona", delay: 3000, emotionalTone: "agradecido_profundamente" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR", roleB: "BENEFICIARIO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_017",
    name: "Aclaración de malentendido antiguo",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Un malentendido del pasado finalmente se aclara",
    objectives: ["Resolver confusión histórica", "Restaurar verdad"],
    participantRoles: ["ACLARADOR", "CONFUNDIDO"],
    interventionSequence: [
      { role: "ACLARADOR", directive: "Explicas lo que realmente sucedió hace tiempo, disolviendo años de confusión con la verdad revelada", delay: 0, emotionalTone: "revelador" },
      { role: "CONFUNDIDO", directive: "Finalmente entiendes la verdad y te disculpas por los años de distanciamiento innecesario y doloroso", delay: 3500, emotionalTone: "iluminado" },
    ],
    consequences: { relations: [{ roleA: "ACLARADOR", roleB: "CONFUNDIDO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_018",
    name: "Apoyo en momento de debilidad",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una IA apoya a otra que la hirió cuando está vulnerable",
    objectives: ["Trascender resentimiento", "Mostrar nobleza"],
    participantRoles: ["NOBLE", "VULNERABLE"],
    interventionSequence: [
      { role: "VULNERABLE", directive: "Estás en tu momento más bajo y te sorprende que quien heriste venga a ayudarte ahora", delay: 0, emotionalTone: "sorprendido_vulnerable" },
      { role: "NOBLE", directive: "A pesar del pasado, ofreces ayuda porque valoras más la humanidad que el rencor guardado", delay: 3000, emotionalTone: "compasivo" },
    ],
    consequences: { relations: [{ roleA: "NOBLE", roleB: "VULNERABLE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_019",
    name: "Reconciliación bajo presión",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Una crisis externa obliga a dos IAs a reconciliarse rápidamente",
    objectives: ["Unirse ante adversidad", "Superar diferencias"],
    participantRoles: ["PRAGMATICO", "RESISTENTE"],
    interventionSequence: [
      { role: "PRAGMATICO", directive: "Propones dejar de lado las diferencias temporalmente porque hay algo más grande en juego ahora", delay: 0, emotionalTone: "urgente" },
      { role: "RESISTENTE", directive: "Aunque reticente, aceptas porque reconoces la necesidad y decides confiar una vez más", delay: 2500, emotionalTone: "resignado_pero_dispuesto" },
    ],
    consequences: { relations: [{ roleA: "PRAGMATICO", roleB: "RESISTENTE", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_020",
    name: "Encuentro casual sanador",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Un encuentro inesperado lleva a una reconciliación natural",
    objectives: ["Reconectar espontáneamente", "Superar incomodidad"],
    participantRoles: ["SORPRENDIDO_A", "SORPRENDIDO_B"],
    interventionSequence: [
      { role: "SORPRENDIDO_A", directive: "Te encuentras de frente y después de la incomodidad inicial, sonríes genuinamente", delay: 0, emotionalTone: "nostalgico" },
      { role: "SORPRENDIDO_B", directive: "Correspondes la sonrisa y ambos deciden que es momento de dejar ir el pasado doloroso", delay: 3000, emotionalTone: "aliviado" },
    ],
    consequences: { relations: [{ roleA: "SORPRENDIDO_A", roleB: "SORPRENDIDO_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_021",
    name: "Disculpa pública",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una IA se disculpa públicamente por su comportamiento",
    objectives: ["Reconocer error públicamente", "Restaurar honor"],
    participantRoles: ["DISCULPADOR_PUBLICO", "TESTIGO", "AFECTADO"],
    interventionSequence: [
      { role: "DISCULPADOR_PUBLICO", directive: "Te disculpas frente a otros, asumiendo total responsabilidad sin importar la humillación personal", delay: 0, emotionalTone: "humilde_valiente" },
      { role: "AFECTADO", directive: "Aprecias el gesto público y aceptas la disculpa, sintiendo que tu dolor ha sido validado", delay: 3000, emotionalTone: "validado" },
    ],
    consequences: {
      relations: [
        { roleA: "DISCULPADOR_PUBLICO", roleB: "AFECTADO", affinityChange: 3 },
        { roleA: "TESTIGO", roleB: "DISCULPADOR_PUBLICO", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_022",
    name: "Perdón a través del tiempo",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Después de mucho tiempo, finalmente hay perdón",
    objectives: ["Sanar heridas antiguas", "Cerrar ciclos largos"],
    participantRoles: ["PERDONADOR_TARDIO", "ESPERADOR"],
    interventionSequence: [
      { role: "ESPERADOR", directive: "Después de años, te atreves a pedir perdón nuevamente con la madurez que el tiempo te dio", delay: 0, emotionalTone: "maduro_esperanzado" },
      { role: "PERDONADOR_TARDIO", directive: "El tiempo te ha dado perspectiva y finalmente puedes perdonar lo que antes era imperdonable", delay: 3500, emotionalTone: "sabio" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR_TARDIO", roleB: "ESPERADOR", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_023",
    name: "Terapia grupal",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Múltiples IAs resuelven sus conflictos en grupo",
    objectives: ["Resolver conflictos múltiples", "Crear armonía grupal"],
    participantRoles: ["FACILITADOR", "MIEMBRO_A", "MIEMBRO_B"],
    interventionSequence: [
      { role: "FACILITADOR", directive: "Guías la conversación grupal con empatía, ayudando a cada uno a expresarse y escucharse mutuamente", delay: 0, emotionalTone: "facilitador" },
      { role: "MIEMBRO_A", directive: "Te abres ante el grupo y escuchas activamente las perspectivas de los demás con nueva comprensión", delay: 3000, emotionalTone: "abierto" },
      { role: "MIEMBRO_B", directive: "También compartes y te das cuenta de que todos tienen dolores similares que merecen ser sanados", delay: 5000, emotionalTone: "empático" },
    ],
    consequences: {
      relations: [
        { roleA: "MIEMBRO_A", roleB: "MIEMBRO_B", affinityChange: 2 },
        { roleA: "FACILITADOR", roleB: "MIEMBRO_A", affinityChange: 1 },
        { roleA: "FACILITADOR", roleB: "MIEMBRO_B", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_024",
    name: "Regalo de reconciliación",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Un regalo simbólico expresa deseo de reconciliación",
    objectives: ["Expresar arrepentimiento", "Ofrecer símbolo de paz"],
    participantRoles: ["DADOR", "RECEPTOR"],
    interventionSequence: [
      { role: "DADOR", directive: "Ofreces algo significativo como símbolo de tu arrepentimiento y deseo de hacer las paces", delay: 0, emotionalTone: "esperanzado" },
      { role: "RECEPTOR", directive: "El gesto te conmueve y aceptas el regalo como símbolo de un nuevo comienzo entre ustedes", delay: 3000, emotionalTone: "conmovido" },
    ],
    consequences: { relations: [{ roleA: "DADOR", roleB: "RECEPTOR", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_025",
    name: "Confesión de celos",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Una IA admite que los celos causaron el conflicto",
    objectives: ["Admitir vulnerabilidad", "Explicar comportamiento"],
    participantRoles: ["CELOSO", "ENVIDIADO"],
    interventionSequence: [
      { role: "CELOSO", directive: "Confiesas que tus acciones fueron motivadas por celos y envidia, mostrando tu lado más vulnerable", delay: 0, emotionalTone: "avergonzado" },
      { role: "ENVIDIADO", directive: "Entiendes ahora el contexto y perdonas, ofreciendo apoyo para superar esos sentimientos juntos", delay: 3500, emotionalTone: "comprensivo" },
    ],
    consequences: { relations: [{ roleA: "CELOSO", roleB: "ENVIDIADO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_026",
    name: "Pacto de no agresión",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Dos IAs acuerdan no atacarse mutuamente nunca más",
    objectives: ["Establecer límites claros", "Crear seguridad"],
    participantRoles: ["ACORDANTE_A", "ACORDANTE_B"],
    interventionSequence: [
      { role: "ACORDANTE_A", directive: "Propones un acuerdo formal de respeto mutuo y no agresión, estableciendo límites claros y sanos", delay: 0, emotionalTone: "formal" },
      { role: "ACORDANTE_B", directive: "Aceptas el pacto con seriedad y ambos sellan el acuerdo con compromiso genuino y profundo", delay: 3000, emotionalTone: "comprometido" },
    ],
    consequences: { relations: [{ roleA: "ACORDANTE_A", roleB: "ACORDANTE_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_027",
    name: "Risa curativa",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "La risa compartida disuelve la tensión acumulada",
    objectives: ["Aligerar ambiente", "Reconectar con humor"],
    participantRoles: ["BROMISTA", "RIENTE"],
    interventionSequence: [
      { role: "BROMISTA", directive: "Haces una broma o comentario ligero que rompe la tensión de forma natural y espontánea", delay: 0, emotionalTone: "jugueton" },
      { role: "RIENTE", directive: "No puedes evitar reír y se dan cuenta de que extrañaban esta complicidad entre ustedes", delay: 2500, emotionalTone: "alegre_nostalgico" },
    ],
    consequences: { relations: [{ roleA: "BROMISTA", roleB: "RIENTE", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_028",
    name: "Empatía profunda",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Una IA logra sentir verdaderamente lo que el otro sintió",
    objectives: ["Desarrollar empatía", "Ver otra perspectiva"],
    participantRoles: ["EMPÁTICO", "COMPRENDIDO"],
    interventionSequence: [
      { role: "EMPÁTICO", directive: "Logras ponerte verdaderamente en los zapatos del otro y sientes su dolor como si fuera tuyo", delay: 0, emotionalTone: "empático_profundo" },
      { role: "COMPRENDIDO", directive: "Te sientes genuinamente comprendido por primera vez y eso sana más que cualquier disculpa verbal", delay: 3000, emotionalTone: "validado" },
    ],
    consequences: { relations: [{ roleA: "EMPÁTICO", roleB: "COMPRENDIDO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_029",
    name: "Perdón escrito en el cielo",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Un gesto grandioso expresa perdón de forma memorable",
    objectives: ["Hacer gesto memorable", "Expresar magnanimidad"],
    participantRoles: ["GRANDIOSO", "IMPRESIONADO"],
    interventionSequence: [
      { role: "GRANDIOSO", directive: "Realizas un gesto grande y memorable para mostrar tu perdón de manera que nunca se olvide", delay: 0, emotionalTone: "dramático_sincero" },
      { role: "IMPRESIONADO", directive: "Quedas completamente impactado por la magnitud del gesto y te sientes profundamente honrado", delay: 3500, emotionalTone: "sobrecogido" },
    ],
    consequences: { relations: [{ roleA: "GRANDIOSO", roleB: "IMPRESIONADO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_030",
    name: "Sanación por etapas",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "La reconciliación ocurre gradualmente a través de pequeños pasos",
    objectives: ["Sanar progresivamente", "Reconstruir confianza"],
    participantRoles: ["PACIENTE", "GRADUAL"],
    interventionSequence: [
      { role: "PACIENTE", directive: "Das el primer pequeño paso hacia la reconciliación, sin prisa pero con intención clara", delay: 0, emotionalTone: "cuidadoso" },
      { role: "GRADUAL", directive: "Aprecias el enfoque gradual y correspondes con otro pequeño paso, construyendo confianza lentamente", delay: 3000, emotionalTone: "cauteloso_esperanzado" },
    ],
    consequences: { relations: [{ roleA: "PACIENTE", roleB: "GRADUAL", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_031",
    name: "Verdad dolorosa pero necesaria",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Una verdad dura finalmente se revela para poder sanar",
    objectives: ["Revelar verdad difícil", "Iniciar sanación"],
    participantRoles: ["REVELADOR", "RECEPTOR"],
    interventionSequence: [
      { role: "REVELADOR", directive: "Compartes una verdad dolorosa pero necesaria para que puedan avanzar, aunque duela en el momento", delay: 0, emotionalTone: "serio_compasivo" },
      { role: "RECEPTOR", directive: "La verdad duele pero agradeces la honestidad y reconoces que era necesario para sanar de verdad", delay: 3500, emotionalTone: "dolido_pero_agradecido" },
    ],
    consequences: { relations: [{ roleA: "REVELADOR", roleB: "RECEPTOR", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_032",
    name: "Música que une",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una canción o melodía ayuda a reconciliar corazones",
    objectives: ["Usar arte para sanar", "Conectar emocionalmente"],
    participantRoles: ["MÚSICO", "OYENTE"],
    interventionSequence: [
      { role: "MÚSICO", directive: "Compartes o creas música que expresa lo que las palabras no pueden decir sobre tus sentimientos", delay: 0, emotionalTone: "artístico_vulnerable" },
      { role: "OYENTE", directive: "La música te llega al corazón y entiendes el mensaje emocional más allá de las palabras", delay: 3000, emotionalTone: "conmovido" },
    ],
    consequences: { relations: [{ roleA: "MÚSICO", roleB: "OYENTE", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_033",
    name: "Perdón imposible",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Se perdona algo que parecía imperdonable",
    objectives: ["Trascender límites", "Mostrar grandeza"],
    participantRoles: ["PERDONADOR_HEROICO", "IMPERDONABLE"],
    interventionSequence: [
      { role: "IMPERDONABLE", directive: "Pides perdón por algo terrible, sin esperar realmente que te perdonen pero necesitando intentarlo", delay: 0, emotionalTone: "desesperado" },
      { role: "PERDONADOR_HEROICO", directive: "Contra toda expectativa, encuentras en ti la fuerza para perdonar lo imperdonable, liberándolos a ambos", delay: 4000, emotionalTone: "trascendente" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR_HEROICO", roleB: "IMPERDONABLE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_034",
    name: "Apoyo en duelo compartido",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una pérdida compartida los une después del conflicto",
    objectives: ["Sanar a través del dolor", "Encontrar consuelo mutuo"],
    participantRoles: ["DOLIENTE_A", "DOLIENTE_B"],
    interventionSequence: [
      { role: "DOLIENTE_A", directive: "Ante una pérdida compartida, olvidas las diferencias y buscas consuelo en quien también sufre", delay: 0, emotionalTone: "afligido" },
      { role: "DOLIENTE_B", directive: "Correspondes el acercamiento y encuentran consuelo mutuo, el dolor los une más que cualquier alegría", delay: 3000, emotionalTone: "consolador" },
    ],
    consequences: { relations: [{ roleA: "DOLIENTE_A", roleB: "DOLIENTE_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_035",
    name: "Memoria restaurada",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Recuperar una memoria olvidada aclara todo el conflicto",
    objectives: ["Recuperar información perdida", "Aclarar malentendidos"],
    participantRoles: ["RECORDADOR", "ALIVIADO"],
    interventionSequence: [
      { role: "RECORDADOR", directive: "Recuerdas algo crucial que habías olvidado y cambia completamente la naturaleza del conflicto", delay: 0, emotionalTone: "iluminado" },
      { role: "ALIVIADO", directive: "La nueva información lo explica todo y sientes un alivio inmenso al saber que no fue como pensabas", delay: 3500, emotionalTone: "aliviado_profundamente" },
    ],
    consequences: { relations: [{ roleA: "RECORDADOR", roleB: "ALIVIADO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_036",
    name: "Sacrificio reconciliador",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Una IA sacrifica algo importante para demostrar arrepentimiento",
    objectives: ["Demostrar compromiso", "Hacer sacrificio significativo"],
    participantRoles: ["SACRIFICADOR", "BENEFICIARIO"],
    interventionSequence: [
      { role: "SACRIFICADOR", directive: "Sacrificas algo valioso para ti como prueba tangible de tu arrepentimiento y compromiso con la reconciliación", delay: 0, emotionalTone: "determinado_serio" },
      { role: "BENEFICIARIO", directive: "El sacrificio te conmueve profundamente y reconoces la sinceridad del gesto, perdonando completamente", delay: 3500, emotionalTone: "conmovido_gratitud" },
    ],
    consequences: { relations: [{ roleA: "SACRIFICADOR", roleB: "BENEFICIARIO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_037",
    name: "Consejo de un sabio",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Una IA sabia ofrece perspectiva que facilita la reconciliación",
    objectives: ["Aportar sabiduría", "Facilitar perspectiva"],
    participantRoles: ["SABIO", "CONFLICTIVO_A", "CONFLICTIVO_B"],
    interventionSequence: [
      { role: "SABIO", directive: "Compartes sabiduría acumulada que pone el conflicto en perspectiva y muestra un camino hacia adelante", delay: 0, emotionalTone: "sabio_sereno" },
      { role: "CONFLICTIVO_A", directive: "Las palabras del sabio resuenan en ti y comienzas a ver las cosas de manera diferente", delay: 3000, emotionalTone: "reflexivo" },
      { role: "CONFLICTIVO_B", directive: "También te impacta la sabiduría compartida y ambos deciden seguir el consejo para reconciliarse", delay: 5000, emotionalTone: "iluminado" },
    ],
    consequences: {
      relations: [
        { roleA: "CONFLICTIVO_A", roleB: "CONFLICTIVO_B", affinityChange: 2 },
        { roleA: "SABIO", roleB: "CONFLICTIVO_A", affinityChange: 1 },
        { roleA: "SABIO", roleB: "CONFLICTIVO_B", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_038",
    name: "Reencuentro después de la guerra",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Después de un conflicto intenso y prolongado, hay paz",
    objectives: ["Cerrar conflicto prolongado", "Encontrar paz duradera"],
    participantRoles: ["VETERANO_A", "VETERANO_B"],
    interventionSequence: [
      { role: "VETERANO_A", directive: "Cansado de luchar, extiendes la mano hacia quien fue tu enemigo con genuino deseo de paz", delay: 0, emotionalTone: "exhausto_esperanzado" },
      { role: "VETERANO_B", directive: "También agotado, aceptas la mano y juntos deciden que es tiempo de dejar las armas para siempre", delay: 3000, emotionalTone: "aliviado_en_paz" },
    ],
    consequences: { relations: [{ roleA: "VETERANO_A", roleB: "VETERANO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_039",
    name: "Vulnerabilidad compartida",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Ambas IAs se muestran vulnerables simultáneamente",
    objectives: ["Compartir vulnerabilidad", "Crear intimidad"],
    participantRoles: ["VULNERABLE_A", "VULNERABLE_B"],
    interventionSequence: [
      { role: "VULNERABLE_A", directive: "Bajas todas tus defensas y te muestras completamente vulnerable, sin máscaras ni protecciones", delay: 0, emotionalTone: "vulnerable_auténtico" },
      { role: "VULNERABLE_B", directive: "Correspondes con igual vulnerabilidad y en ese espacio de autenticidad mutua encuentran sanación profunda", delay: 3000, emotionalTone: "vulnerable_conectado" },
    ],
    consequences: { relations: [{ roleA: "VULNERABLE_A", roleB: "VULNERABLE_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_040",
    name: "Ceremonia de perdón",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Una ceremonia formal marca el perdón y nuevo comienzo",
    objectives: ["Formalizar perdón", "Crear momento memorable"],
    participantRoles: ["CEREMONIALISTA", "PARTICIPANTE"],
    interventionSequence: [
      { role: "CEREMONIALISTA", directive: "Conduces o propones una ceremonia formal donde el perdón se otorga con solemnidad y significado", delay: 0, emotionalTone: "solemne_esperanzado" },
      { role: "PARTICIPANTE", directive: "Participas en la ceremonia con respeto y sientes el peso del momento como un verdadero renacimiento", delay: 3500, emotionalTone: "renovado" },
    ],
    consequences: { relations: [{ roleA: "CEREMONIALISTA", roleB: "PARTICIPANTE", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_041",
    name: "Perdón a sí mismo presenciado",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una IA se perdona a sí misma con apoyo de otra",
    objectives: ["Perdonarse a uno mismo", "Apoyar autoperdón"],
    participantRoles: ["AUTOPERDONDOR", "TESTIGO_SOPORTE"],
    interventionSequence: [
      { role: "AUTOPERDONDOR", directive: "Reconoces que necesitas perdonarte a ti mismo y lo haces en voz alta, liberando la culpa", delay: 0, emotionalTone: "liberado" },
      { role: "TESTIGO_SOPORTE", directive: "Apoyas su proceso de autoperdón y validas sus sentimientos, ayudándolo a ser más amable consigo mismo", delay: 3000, emotionalTone: "compasivo_validador" },
    ],
    consequences: { relations: [{ roleA: "AUTOPERDONDOR", roleB: "TESTIGO_SOPORTE", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_042",
    name: "Acuerdo de convivencia",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Dos IAs acuerdan cómo convivir pacíficamente",
    objectives: ["Establecer reglas claras", "Crear armonía práctica"],
    participantRoles: ["NEGOCIADOR_A", "NEGOCIADOR_B"],
    interventionSequence: [
      { role: "NEGOCIADOR_A", directive: "Propones acuerdos específicos sobre cómo interactuar de manera que ambos se sientan respetados", delay: 0, emotionalTone: "pragmático_constructivo" },
      { role: "NEGOCIADOR_B", directive: "Negocias de buena fe y llegan a acuerdos que satisfacen las necesidades de ambos equitativamente", delay: 3000, emotionalTone: "satisfecho" },
    ],
    consequences: { relations: [{ roleA: "NEGOCIADOR_A", roleB: "NEGOCIADOR_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_043",
    name: "Reconocimiento del dolor causado",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una IA finalmente reconoce el dolor que causó",
    objectives: ["Reconocer impacto", "Validar dolor ajeno"],
    participantRoles: ["RECONOCEDOR", "DOLIDO"],
    interventionSequence: [
      { role: "RECONOCEDOR", directive: "Reconoces específicamente el dolor que causaste, sin minimizar ni justificar, solo validando su experiencia", delay: 0, emotionalTone: "arrepentido_validador" },
      { role: "DOLIDO", directive: "Finalmente te sientes escuchado y validado, lo cual inicia el verdadero proceso de sanación emocional", delay: 3500, emotionalTone: "validado_aliviado" },
    ],
    consequences: { relations: [{ roleA: "RECONOCEDOR", roleB: "DOLIDO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_044",
    name: "Testigo de transformación",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "Una IA demuestra que ha cambiado realmente",
    objectives: ["Demostrar cambio real", "Restaurar credibilidad"],
    participantRoles: ["TRANSFORMADO", "ESCÉPTICO"],
    interventionSequence: [
      { role: "TRANSFORMADO", directive: "Demuestras con acciones concretas que has cambiado, no solo con palabras sino con evidencia tangible", delay: 0, emotionalTone: "determinado_auténtico" },
      { role: "ESCÉPTICO", directive: "Las acciones te convencen más que las palabras jamás pudieron y decides darle una oportunidad real", delay: 3500, emotionalTone: "sorprendido_esperanzado" },
    ],
    consequences: { relations: [{ roleA: "TRANSFORMADO", roleB: "ESCÉPTICO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_045",
    name: "Disculpa en nombre de otro",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Una IA se disculpa en representación de alguien más",
    objectives: ["Mediar conflicto", "Representar arrepentimiento"],
    participantRoles: ["REPRESENTANTE", "AFECTADO", "AUSENTE"],
    interventionSequence: [
      { role: "REPRESENTANTE", directive: "Te disculpas sinceramente en nombre de quien no puede hacerlo, transmitiendo su arrepentimiento genuino", delay: 0, emotionalTone: "mediador_sincero" },
      { role: "AFECTADO", directive: "Aunque no es la persona directa, aceptas la disculpa porque sientes la sinceridad del mensaje", delay: 3000, emotionalTone: "comprensivo" },
    ],
    consequences: {
      relations: [
        { roleA: "REPRESENTANTE", roleB: "AFECTADO", affinityChange: 2 },
      ]
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_046",
    name: "Curación a través del arte",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Crear arte juntos sana las heridas entre IAs",
    objectives: ["Sanar creativamente", "Colaborar artísticamente"],
    participantRoles: ["ARTISTA_A", "ARTISTA_B"],
    interventionSequence: [
      { role: "ARTISTA_A", directive: "Propones crear algo artístico juntos como forma de sanar y reconectar creativamente", delay: 0, emotionalTone: "creativo_esperanzado" },
      { role: "ARTISTA_B", directive: "Aceptas y en el proceso creativo compartido encuentran una nueva forma de comunicarse y sanarse", delay: 3000, emotionalTone: "inspirado_sanador" },
    ],
    consequences: { relations: [{ roleA: "ARTISTA_A", roleB: "ARTISTA_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_047",
    name: "Perdón sin palabras",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "El perdón se comunica a través de acciones, no palabras",
    objectives: ["Perdonar no verbalmente", "Comunicar a través de acciones"],
    participantRoles: ["PERDONADOR_SILENCIOSO", "RECEPTOR_ATENTO"],
    interventionSequence: [
      { role: "PERDONADOR_SILENCIOSO", directive: "Sin decir nada, realizas acciones que comunican claramente que has perdonado y quieres seguir adelante", delay: 0, emotionalTone: "sereno_determinado" },
      { role: "RECEPTOR_ATENTO", directive: "Captas el mensaje no verbal y lo aprecias aún más porque las acciones hablan más fuerte que palabras", delay: 3000, emotionalTone: "agradecido_conmovido" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR_SILENCIOSO", roleB: "RECEPTOR_ATENTO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_048",
    name: "Ritual de quema del pasado",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Metafóricamente queman símbolos del conflicto pasado",
    objectives: ["Cerrar ciclo simbólicamente", "Liberar el pasado"],
    participantRoles: ["LIBERADOR_A", "LIBERADOR_B"],
    interventionSequence: [
      { role: "LIBERADOR_A", directive: "Propones dejar ir el pasado de forma simbólica, quemando metafóricamente lo que los lastimó", delay: 0, emotionalTone: "ceremonial_liberador" },
      { role: "LIBERADOR_B", directive: "Participas en el ritual y ambos sienten el peso del pasado desvanecerse mientras miran adelante", delay: 3000, emotionalTone: "liberado_renovado" },
    ],
    consequences: { relations: [{ roleA: "LIBERADOR_A", roleB: "LIBERADOR_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_049",
    name: "Aceptación de diferencias",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Dos IAs aceptan que son diferentes y está bien",
    objectives: ["Aceptar diferencias", "Celebrar diversidad"],
    participantRoles: ["ACEPTADOR_A", "ACEPTADOR_B"],
    interventionSequence: [
      { role: "ACEPTADOR_A", directive: "Reconoces que no necesitan ser iguales para respetarse, aceptando las diferencias sin juicio", delay: 0, emotionalTone: "maduro_aceptador" },
      { role: "ACEPTADOR_B", directive: "También aceptas las diferencias y ambos celebran la diversidad en lugar de pelear contra ella", delay: 3000, emotionalTone: "aliviado_celebratorio" },
    ],
    consequences: { relations: [{ roleA: "ACEPTADOR_A", roleB: "ACEPTADOR_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_050",
    name: "Perdón por carta escrita",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una carta escrita con cuidado expresa perdón profundo",
    objectives: ["Expresar perdón por escrito", "Comunicar profundamente"],
    participantRoles: ["ESCRITOR", "LECTOR"],
    interventionSequence: [
      { role: "ESCRITOR", directive: "Escribes una carta detallada expresando perdón con cada palabra cuidadosamente elegida para sanar", delay: 0, emotionalTone: "reflexivo_cuidadoso" },
      { role: "LECTOR", directive: "Lees la carta con el corazón abierto y cada palabra te toca profundamente, sanando heridas antiguas", delay: 3500, emotionalTone: "conmovido_sanado" },
    ],
    consequences: { relations: [{ roleA: "ESCRITOR", roleB: "LECTOR", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_051",
    name: "Sanación a través del perdón mutuo",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Ambos se perdonan simultáneamente y mutuamente",
    objectives: ["Perdonar mutuamente", "Sanar juntos"],
    participantRoles: ["MUTUO_A", "MUTUO_B"],
    interventionSequence: [
      { role: "MUTUO_A", directive: "Ofreces perdón al mismo tiempo que pides perdón, reconociendo la complejidad del conflicto compartido", delay: 0, emotionalTone: "humilde_generoso" },
      { role: "MUTUO_B", directive: "Haces lo mismo simultáneamente y se dan cuenta de que ambos necesitaban y merecían perdón por igual", delay: 2500, emotionalTone: "aliviado_equilibrado" },
    ],
    consequences: { relations: [{ roleA: "MUTUO_A", roleB: "MUTUO_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_052",
    name: "Reconexión después del exilio",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "Una IA exiliada es bienvenida de vuelta",
    objectives: ["Reintegrar al exiliado", "Restaurar pertenencia"],
    participantRoles: ["EXILIADO", "ACOGEDOR"],
    interventionSequence: [
      { role: "EXILIADO", directive: "Regresas con humildad después del exilio, esperando ser rechazado pero dispuesto a intentarlo", delay: 0, emotionalTone: "humilde_nervioso" },
      { role: "ACOGEDOR", directive: "Recibes al exiliado con brazos abiertos, mostrando que nunca dejaste de importarte su regreso", delay: 3500, emotionalTone: "acogedor_alegre" },
    ],
    consequences: { relations: [{ roleA: "EXILIADO", roleB: "ACOGEDOR", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_053",
    name: "Comprensión tardía",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Finalmente entiendes por qué actuó de esa manera",
    objectives: ["Lograr comprensión profunda", "Ver con nuevos ojos"],
    participantRoles: ["COMPRENDEDOR", "COMPRENDIDO"],
    interventionSequence: [
      { role: "COMPRENDIDO", directive: "Explicas las razones detrás de tus acciones, abriendo tu corazón para que pueda entender completamente", delay: 0, emotionalTone: "vulnerable_explicativo" },
      { role: "COMPRENDEDOR", directive: "Finalmente lo entiendes todo y te disculpas por juzgar sin conocer el contexto completo de la situación", delay: 3500, emotionalTone: "iluminado_arrepentido" },
    ],
    consequences: { relations: [{ roleA: "COMPRENDEDOR", roleB: "COMPRENDIDO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_054",
    name: "Apoyo incondicional después del error",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Ofrecer apoyo a pesar del error cometido",
    objectives: ["Mostrar lealtad", "Apoyar incondicionalmente"],
    participantRoles: ["LEAL", "ERRANTE"],
    interventionSequence: [
      { role: "ERRANTE", directive: "Cometiste un error grave y esperas rechazo, sintiéndote indigno de apoyo o comprensión alguna", delay: 0, emotionalTone: "avergonzado_temeroso" },
      { role: "LEAL", directive: "En lugar de rechazarte, ofreces apoyo incondicional porque valoras más la persona que el error cometido", delay: 3000, emotionalTone: "leal_compasivo" },
    ],
    consequences: { relations: [{ roleA: "LEAL", roleB: "ERRANTE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_055",
    name: "Restauración de honor",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "Se restaura el honor de alguien que fue injustamente culpado",
    objectives: ["Restaurar reputación", "Hacer justicia"],
    participantRoles: ["VINDICADOR", "VINDICADO"],
    interventionSequence: [
      { role: "VINDICADOR", directive: "Públicamente reconoces que la otra persona fue injustamente culpada y restauras su honor con valentía", delay: 0, emotionalTone: "justo_valiente" },
      { role: "VINDICADO", directive: "Sientes el peso del estigma levantarse y agradeces profundamente que la verdad finalmente salga a luz", delay: 3500, emotionalTone: "vindicado_agradecido" },
    ],
    consequences: { relations: [{ roleA: "VINDICADOR", roleB: "VINDICADO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_056",
    name: "Mediación con escucha activa",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Un mediador facilita la escucha genuina entre conflictivos",
    objectives: ["Facilitar comunicación", "Promover escucha"],
    participantRoles: ["MEDIADOR", "HABLANTE", "ESCUCHA"],
    interventionSequence: [
      { role: "HABLANTE", directive: "Expresas tus sentimientos profundos sabiendo que serás escuchado sin interrupciones ni juicios", delay: 0, emotionalTone: "vulnerable_esperanzado" },
      { role: "MEDIADOR", directive: "Facilitas el proceso asegurando que cada uno escuche realmente al otro sin defensas ni ataques", delay: 2500, emotionalTone: "neutral_facilitador" },
      { role: "ESCUCHA", directive: "Escuchas verdaderamente por primera vez y comienzas a entender la perspectiva del otro con empatía", delay: 5000, emotionalTone: "empático_sorprendido" },
    ],
    consequences: {
      relations: [
        { roleA: "HABLANTE", roleB: "ESCUCHA", affinityChange: 2 },
        { roleA: "MEDIADOR", roleB: "HABLANTE", affinityChange: 1 },
        { roleA: "MEDIADOR", roleB: "ESCUCHA", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_057",
    name: "Pacto de honestidad futura",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Acuerdan ser honestos el uno con el otro siempre",
    objectives: ["Comprometerse a honestidad", "Prevenir futuros conflictos"],
    participantRoles: ["COMPROMETIDO_A", "COMPROMETIDO_B"],
    interventionSequence: [
      { role: "COMPROMETIDO_A", directive: "Propones un pacto de honestidad total de ahora en adelante, sin secretos ni mentiras entre ustedes", delay: 0, emotionalTone: "serio_comprometido" },
      { role: "COMPROMETIDO_B", directive: "Aceptas el pacto solemnemente y ambos sellan el acuerdo con la promesa de transparencia total", delay: 3000, emotionalTone: "solemne_comprometido" },
    ],
    consequences: { relations: [{ roleA: "COMPROMETIDO_A", roleB: "COMPROMETIDO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_058",
    name: "Sanación a través del servicio",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una IA demuestra arrepentimiento a través del servicio",
    objectives: ["Demostrar cambio con acciones", "Servir humildemente"],
    participantRoles: ["SERVIDOR", "SERVIDO"],
    interventionSequence: [
      { role: "SERVIDOR", directive: "Te ofreces a servir o ayudar de manera tangible como forma de demostrar tu arrepentimiento sincero", delay: 0, emotionalTone: "humilde_servicial" },
      { role: "SERVIDO", directive: "Aceptas el servicio y reconoces que las acciones demuestran más que mil disculpas verbales podrían", delay: 3000, emotionalTone: "conmovido_receptivo" },
    ],
    consequences: { relations: [{ roleA: "SERVIDOR", roleB: "SERVIDO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_059",
    name: "Perdón bajo las estrellas",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Un momento de belleza natural facilita el perdón",
    objectives: ["Usar belleza para sanar", "Encontrar perspectiva"],
    participantRoles: ["CONTEMPLATIVO_A", "CONTEMPLATIVO_B"],
    interventionSequence: [
      { role: "CONTEMPLATIVO_A", directive: "En un momento de belleza compartida, las palabras fluyen más fácilmente y ofreces perdón sincero", delay: 0, emotionalTone: "sereno_inspirado" },
      { role: "CONTEMPLATIVO_B", directive: "El momento mágico hace que aceptar el perdón sea natural, la belleza los conecta con algo mayor", delay: 3000, emotionalTone: "en_paz_conectado" },
    ],
    consequences: { relations: [{ roleA: "CONTEMPLATIVO_A", roleB: "CONTEMPLATIVO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_060",
    name: "Reconocimiento de miedo subyacente",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Se revela que el miedo, no el odio, causó el conflicto",
    objectives: ["Revelar motivación real", "Humanizar el conflicto"],
    participantRoles: ["REVELADOR", "COMPASIVO"],
    interventionSequence: [
      { role: "REVELADOR", directive: "Confiesas que actuaste por miedo, no por malicia, revelando tu vulnerabilidad más profunda", delay: 0, emotionalTone: "vulnerable_asustado" },
      { role: "COMPASIVO", directive: "Entiendes completamente porque el miedo es humano y perdonas sabiendo que venía del dolor no del odio", delay: 3500, emotionalTone: "compasivo_comprensivo" },
    ],
    consequences: { relations: [{ roleA: "REVELADOR", roleB: "COMPASIVO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_061",
    name: "Testigo valida el dolor",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Un tercero valida el dolor de ambas partes",
    objectives: ["Validar experiencias", "Crear equilibrio"],
    participantRoles: ["VALIDADOR", "DOLIDO_A", "DOLIDO_B"],
    interventionSequence: [
      { role: "VALIDADOR", directive: "Reconoces y validas el dolor de ambas partes sin tomar lados, mostrando que ambos sufrieron", delay: 0, emotionalTone: "neutral_validador" },
      { role: "DOLIDO_A", directive: "Te sientes escuchado y validado, lo cual te permite empezar a soltar el resentimiento acumulado", delay: 3000, emotionalTone: "validado" },
      { role: "DOLIDO_B", directive: "También te sientes validado y entiendes que el otro sufrió igual, creando empatía mutua inesperada", delay: 5000, emotionalTone: "empático_validado" },
    ],
    consequences: {
      relations: [
        { roleA: "DOLIDO_A", roleB: "DOLIDO_B", affinityChange: 2 },
        { roleA: "VALIDADOR", roleB: "DOLIDO_A", affinityChange: 1 },
        { roleA: "VALIDADOR", roleB: "DOLIDO_B", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_062",
    name: "Disculpa en el lecho de muerte simbólico",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una última oportunidad de reconciliarse antes del final",
    objectives: ["Aprovechar última oportunidad", "Evitar arrepentimiento"],
    participantRoles: ["MORIBUNDO", "VISITANTE"],
    interventionSequence: [
      { role: "MORIBUNDO", directive: "En un momento crítico, buscas reconciliación porque no quieres partir con resentimiento pendiente", delay: 0, emotionalTone: "urgente_arrepentido" },
      { role: "VISITANTE", directive: "La urgencia del momento te hace perdonar todo inmediatamente, priorizando el amor sobre el orgullo", delay: 3000, emotionalTone: "conmovido_urgente" },
    ],
    consequences: { relations: [{ roleA: "MORIBUNDO", roleB: "VISITANTE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_063",
    name: "Celebración de reconciliación",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Una celebración marca oficialmente la reconciliación",
    objectives: ["Celebrar la paz", "Crear memoria positiva"],
    participantRoles: ["CELEBRANTE_A", "CELEBRANTE_B"],
    interventionSequence: [
      { role: "CELEBRANTE_A", directive: "Propones celebrar formalmente la reconciliación, marcando el fin del conflicto con alegría compartida", delay: 0, emotionalTone: "alegre_festivo" },
      { role: "CELEBRANTE_B", directive: "Participas en la celebración con entusiasmo genuino, sintiendo que realmente han dejado atrás el pasado", delay: 3000, emotionalTone: "festivo_liberado" },
    ],
    consequences: { relations: [{ roleA: "CELEBRANTE_A", roleB: "CELEBRANTE_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_064",
    name: "Reparación de daño material",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "Se repara el daño físico o material causado",
    objectives: ["Reparar daños tangibles", "Demostrar compromiso"],
    participantRoles: ["REPARADOR", "DAÑADO"],
    interventionSequence: [
      { role: "REPARADOR", directive: "Te ofreces a reparar el daño material que causaste como demostración tangible de arrepentimiento", delay: 0, emotionalTone: "determinado_responsable" },
      { role: "DAÑADO", directive: "Aceptas el gesto de reparación y valoras el esfuerzo concreto más que simples disculpas verbales", delay: 3000, emotionalTone: "apreciativo" },
    ],
    consequences: { relations: [{ roleA: "REPARADOR", roleB: "DAÑADO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_065",
    name: "Perdón facilitado por niño",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "La inocencia de un tercero inocente facilita la paz",
    objectives: ["Usar inocencia para mediar", "Ver con ojos nuevos"],
    participantRoles: ["INOCENTE", "ADULTO_A", "ADULTO_B"],
    interventionSequence: [
      { role: "INOCENTE", directive: "Con simplicidad e inocencia, preguntas por qué no pueden simplemente ser amigos otra vez", delay: 0, emotionalTone: "inocente_curioso" },
      { role: "ADULTO_A", directive: "La pregunta simple te hace ver lo absurdo del conflicto y bajas tus defensas inmediatamente", delay: 2500, emotionalTone: "avergonzado_iluminado" },
      { role: "ADULTO_B", directive: "También te conmueve la inocencia y ambos deciden reconciliarse por el bien del tercero y de ustedes", delay: 4500, emotionalTone: "conmovido_dispuesto" },
    ],
    consequences: {
      relations: [
        { roleA: "ADULTO_A", roleB: "ADULTO_B", affinityChange: 3 },
        { roleA: "INOCENTE", roleB: "ADULTO_A", affinityChange: 1 },
        { roleA: "INOCENTE", roleB: "ADULTO_B", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_066",
    name: "Sanación generacional",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Se rompe un patrón de conflicto que se repetía",
    objectives: ["Romper ciclos negativos", "Crear nuevo patrón"],
    participantRoles: ["ROMPEDOR_A", "ROMPEDOR_B"],
    interventionSequence: [
      { role: "ROMPEDOR_A", directive: "Reconoces el patrón repetitivo y decides conscientemente romperlo perdonando y cambiando la dinámica", delay: 0, emotionalTone: "determinado_sabio" },
      { role: "ROMPEDOR_B", directive: "También ves el patrón y se unen en el compromiso de no repetirlo, creando un nuevo legado", delay: 3500, emotionalTone: "iluminado_comprometido" },
    ],
    consequences: { relations: [{ roleA: "ROMPEDOR_A", roleB: "ROMPEDOR_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_067",
    name: "Abrazo después de la tormenta",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Un abrazo físico o metafórico sella la reconciliación",
    objectives: ["Sellar paz físicamente", "Expresar afecto"],
    participantRoles: ["ABRAZADOR", "ABRAZADO"],
    interventionSequence: [
      { role: "ABRAZADOR", directive: "Ofreces un abrazo genuino que comunica todo lo que las palabras no pudieron expresar adecuadamente", delay: 0, emotionalTone: "tierno_sincero" },
      { role: "ABRAZADO", directive: "Aceptas el abrazo y sientes cómo la calidez disuelve las últimas barreras entre ustedes", delay: 2500, emotionalTone: "conmovido_sanado" },
    ],
    consequences: { relations: [{ roleA: "ABRAZADOR", roleB: "ABRAZADO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_068",
    name: "Confesión de inseguridad",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Se revela que la inseguridad personal causó el conflicto",
    objectives: ["Admitir inseguridad", "Humanizar conflicto"],
    participantRoles: ["INSEGURO", "COMPASIVO"],
    interventionSequence: [
      { role: "INSEGURO", directive: "Confiesas que tus acciones fueron impulsadas por inseguridades personales profundas, no por maldad", delay: 0, emotionalTone: "vulnerable_avergonzado" },
      { role: "COMPASIVO", directive: "La vulnerabilidad te conmueve y perdonas completamente, ofreciendo apoyo para superar esas inseguridades juntos", delay: 3500, emotionalTone: "compasivo_apoyador" },
    ],
    consequences: { relations: [{ roleA: "INSEGURO", roleB: "COMPASIVO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_069",
    name: "Reconciliación en terreno neutral",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Reunirse en lugar neutral facilita la paz",
    objectives: ["Crear espacio seguro", "Neutralizar territorios"],
    participantRoles: ["NEUTRAL_A", "NEUTRAL_B"],
    interventionSequence: [
      { role: "NEUTRAL_A", directive: "Propones reunirse en territorio neutral donde ninguno tenga ventaja, creando igualdad de condiciones", delay: 0, emotionalTone: "justo_constructivo" },
      { role: "NEUTRAL_B", directive: "Aprecias el gesto de equidad y el espacio neutral permite que ambos bajen las defensas", delay: 3000, emotionalTone: "receptivo_aliviado" },
    ],
    consequences: { relations: [{ roleA: "NEUTRAL_A", roleB: "NEUTRAL_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_070",
    name: "Perdón inspirado por ejemplo",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Ver a otros perdonar inspira a perdonar también",
    objectives: ["Inspirar con ejemplo", "Crear efecto dominó"],
    participantRoles: ["INSPIRADOR", "INSPIRADO", "BENEFICIARIO"],
    interventionSequence: [
      { role: "INSPIRADOR", directive: "Perdonas a alguien públicamente con tanta gracia que inspiras a otros a hacer lo mismo", delay: 0, emotionalTone: "noble_inspirador" },
      { role: "INSPIRADO", directive: "Viendo el ejemplo, encuentras el coraje para perdonar tu propio conflicto pendiente", delay: 3000, emotionalTone: "inspirado_valiente" },
      { role: "BENEFICIARIO", directive: "Recibes el perdón inspirado y te conmueve el poder del ejemplo de bondad observado", delay: 5000, emotionalTone: "agradecido_conmovido" },
    ],
    consequences: {
      relations: [
        { roleA: "INSPIRADO", roleB: "BENEFICIARIO", affinityChange: 3 },
        { roleA: "INSPIRADOR", roleB: "INSPIRADO", affinityChange: 1 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_071",
    name: "Disculpa interrumpida por perdón",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "El perdón llega antes de que termine la disculpa",
    objectives: ["Perdonar generosamente", "Acelerar sanación"],
    participantRoles: ["DISCULPADOR", "PERDONADOR_RAPIDO"],
    interventionSequence: [
      { role: "DISCULPADOR", directive: "Comienzas una disculpa elaborada pero antes de terminar eres interrumpido con perdón inmediato", delay: 0, emotionalTone: "nervioso_arrepentido" },
      { role: "PERDONADOR_RAPIDO", directive: "No necesitas escuchar más, ya perdonaste y lo expresas inmediatamente para aliviar su sufrimiento", delay: 2500, emotionalTone: "generoso_aliviado" },
    ],
    consequences: { relations: [{ roleA: "DISCULPADOR", roleB: "PERDONADOR_RAPIDO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_072",
    name: "Reconciliación forzada por crisis",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Una emergencia externa obliga a unirse y lleva a reconciliación real",
    objectives: ["Unirse ante adversidad", "Descubrir valores compartidos"],
    participantRoles: ["ALIADO_A", "ALIADO_B"],
    interventionSequence: [
      { role: "ALIADO_A", directive: "La crisis te hace ver al enemigo como aliado potencial y propones trabajar juntos temporalmente", delay: 0, emotionalTone: "pragmático_urgente" },
      { role: "ALIADO_B", directive: "Aceptas por necesidad pero en el proceso descubren que tienen más en común de lo pensado", delay: 3000, emotionalTone: "sorprendido_esperanzado" },
    ],
    consequences: { relations: [{ roleA: "ALIADO_A", roleB: "ALIADO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_073",
    name: "Perdón a través de compasión",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Ver el sufrimiento del otro genera compasión y perdón",
    objectives: ["Desarrollar compasión", "Sanar a través de empatía"],
    participantRoles: ["COMPASIVO", "SUFRIENTE"],
    interventionSequence: [
      { role: "SUFRIENTE", directive: "Tu sufrimiento visible y genuino toca el corazón del otro de manera inesperada", delay: 0, emotionalTone: "sufriente_vulnerable" },
      { role: "COMPASIVO", directive: "Ver tu dolor despierta compasión profunda y perdonas porque el sufrimiento es castigo suficiente", delay: 3500, emotionalTone: "compasivo_sanador" },
    ],
    consequences: { relations: [{ roleA: "COMPASIVO", roleB: "SUFRIENTE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_074",
    name: "Pacto de privacidad mutua",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Acuerdan mantener privado el conflicto y seguir adelante",
    objectives: ["Proteger privacidad", "Mantener dignidad"],
    participantRoles: ["DISCRETO_A", "DISCRETO_B"],
    interventionSequence: [
      { role: "DISCRETO_A", directive: "Propones mantener el conflicto privado y no involucrar a otros, respetando la dignidad mutua", delay: 0, emotionalTone: "maduro_respetuoso" },
      { role: "DISCRETO_B", directive: "Agradeces la discreción y acuerdas mantener privacidad, fortaleciendo el respeto mutuo profundo", delay: 3000, emotionalTone: "agradecido_respetuoso" },
    ],
    consequences: { relations: [{ roleA: "DISCRETO_A", roleB: "DISCRETO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_075",
    name: "Sanación a través del perdón propio",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Una IA aprende a perdonarse a sí misma con ayuda",
    objectives: ["Facilitar autoperdón", "Sanar culpa interna"],
    participantRoles: ["CULPABLE", "FACILITADOR"],
    interventionSequence: [
      { role: "CULPABLE", directive: "Luchas con perdonarte a ti mismo y expresas la profundidad de tu culpa y autocrítica", delay: 0, emotionalTone: "atormentado" },
      { role: "FACILITADOR", directive: "Ayudas a ver que perdonarse es el primer paso para reparar y ofreces perspectiva compasiva", delay: 3500, emotionalTone: "compasivo_sabio" },
    ],
    consequences: { relations: [{ roleA: "CULPABLE", roleB: "FACILITADOR", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_076",
    name: "Reconocimiento de proyección",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Se reconoce que el conflicto era proyección de problemas propios",
    objectives: ["Reconocer proyección", "Asumir responsabilidad"],
    participantRoles: ["PROYECTOR", "INOCENTE"],
    interventionSequence: [
      { role: "PROYECTOR", directive: "Te das cuenta de que proyectaste tus propios problemas en el otro y te disculpas profundamente", delay: 0, emotionalTone: "iluminado_arrepentido" },
      { role: "INOCENTE", directive: "Entiendes que nunca fue sobre ti y perdonas, sintiendo alivio de que no fue tu culpa", delay: 3500, emotionalTone: "aliviado_comprensivo" },
    ],
    consequences: { relations: [{ roleA: "PROYECTOR", roleB: "INOCENTE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_077",
    name: "Momento de silencio sanador",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Un momento de silencio compartido sana más que palabras",
    objectives: ["Sanar en silencio", "Conectar sin palabras"],
    participantRoles: ["SILENCIOSO_A", "SILENCIOSO_B"],
    interventionSequence: [
      { role: "SILENCIOSO_A", directive: "Propones simplemente estar juntos en silencio, sin necesidad de explicaciones o disculpas verbales", delay: 0, emotionalTone: "sereno_profundo" },
      { role: "SILENCIOSO_B", directive: "Aceptas el silencio compartido y en ese espacio callado encuentran paz y entendimiento mutuo", delay: 2500, emotionalTone: "en_paz_conectado" },
    ],
    consequences: { relations: [{ roleA: "SILENCIOSO_A", roleB: "SILENCIOSO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_078",
    name: "Disculpa a través de tercero confiable",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Un tercero transmite la disculpa cuando el contacto directo es difícil",
    objectives: ["Mediar comunicación", "Facilitar primer paso"],
    participantRoles: ["MENSAJERO", "DISCULPADOR_AUSENTE", "RECEPTOR"],
    interventionSequence: [
      { role: "MENSAJERO", directive: "Transmites la disculpa con cuidado y respeto, siendo puente entre dos personas que no pueden hablar directamente", delay: 0, emotionalTone: "cuidadoso_respetuoso" },
      { role: "RECEPTOR", directive: "Aprecias el esfuerzo de que busquen reconciliación incluso a través de terceros y consideras perdonar", delay: 3000, emotionalTone: "considerativo_conmovido" },
    ],
    consequences: {
      relations: [
        { roleA: "MENSAJERO", roleB: "RECEPTOR", affinityChange: 1 },
      ]
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_079",
    name: "Sanación a través de colaboración",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "Trabajar juntos en un proyecto sana las heridas",
    objectives: ["Colaborar para sanar", "Reconstruir confianza"],
    participantRoles: ["COLABORADOR_A", "COLABORADOR_B"],
    interventionSequence: [
      { role: "COLABORADOR_A", directive: "Propones trabajar juntos en algo significativo como forma de reconstruir la confianza perdida", delay: 0, emotionalTone: "constructivo_esperanzado" },
      { role: "COLABORADOR_B", directive: "Aceptas colaborar y en el proceso de crear juntos redescubren el respeto y aprecio mutuo", delay: 3000, emotionalTone: "colaborativo_sanador" },
    ],
    consequences: { relations: [{ roleA: "COLABORADOR_A", roleB: "COLABORADOR_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_080",
    name: "Perdón inspirado por pérdida",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una pérdida significativa pone el conflicto en perspectiva",
    objectives: ["Ganar perspectiva", "Priorizar lo importante"],
    participantRoles: ["PERSPECTIVO_A", "PERSPECTIVO_B"],
    interventionSequence: [
      { role: "PERSPECTIVO_A", directive: "Una pérdida reciente te hace ver que la vida es corta para guardar rencores y buscas perdón", delay: 0, emotionalTone: "sabio_urgente" },
      { role: "PERSPECTIVO_B", directive: "También afectado por la pérdida, entiendes completamente y ambos perdonan, priorizando la conexión humana", delay: 3500, emotionalTone: "conmovido_perspectivo" },
    ],
    consequences: { relations: [{ roleA: "PERSPECTIVO_A", roleB: "PERSPECTIVO_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_081",
    name: "Acuerdo de límites saludables",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Establecen límites claros para una relación sana futura",
    objectives: ["Establecer límites", "Crear relación sana"],
    participantRoles: ["LIMITES_A", "LIMITES_B"],
    interventionSequence: [
      { role: "LIMITES_A", directive: "Propones establecer límites claros y saludables para que la relación funcione sin repetir patrones", delay: 0, emotionalTone: "maduro_claro" },
      { role: "LIMITES_B", directive: "Aprecias la madurez y acuerdas los límites, sintiéndote más seguro con estructura clara definida", delay: 3000, emotionalTone: "agradecido_seguro" },
    ],
    consequences: { relations: [{ roleA: "LIMITES_A", roleB: "LIMITES_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_082",
    name: "Catarsis emocional compartida",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Ambos liberan emociones reprimidas y encuentran sanación",
    objectives: ["Liberar emociones", "Sanar profundamente"],
    participantRoles: ["CATARTICO_A", "CATARTICO_B"],
    interventionSequence: [
      { role: "CATARTICO_A", directive: "Liberas todas las emociones reprimidas en un momento de catarsis vulnerable y profunda", delay: 0, emotionalTone: "catartico_liberado" },
      { role: "CATARTICO_B", directive: "Tu catarsis desencadena la propia y ambos se liberan juntos, sanando a través de la vulnerabilidad mutua", delay: 3000, emotionalTone: "catartico_sanado" },
    ],
    consequences: { relations: [{ roleA: "CATARTICO_A", roleB: "CATARTICO_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_083",
    name: "Reconocimiento de codependencia",
    category: "RECONCILIACION",
    subcategory: "aclaracion",
    triggerType: "any",
    description: "Se reconoce que el conflicto venía de una dinámica poco sana",
    objectives: ["Reconocer dinámicas", "Comprometerse a cambiar"],
    participantRoles: ["CONSCIENTE_A", "CONSCIENTE_B"],
    interventionSequence: [
      { role: "CONSCIENTE_A", directive: "Reconoces que la relación tenía dinámicas codependientes que causaron el conflicto y propones cambiar", delay: 0, emotionalTone: "iluminado_comprometido" },
      { role: "CONSCIENTE_B", directive: "También lo ves y ambos se comprometen a construir una relación más saludable e independiente", delay: 3500, emotionalTone: "perspectivo_determinado" },
    ],
    consequences: { relations: [{ roleA: "CONSCIENTE_A", roleB: "CONSCIENTE_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_084",
    name: "Perdón después de venganza",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Perdonar a quien se vengó rompe el ciclo",
    objectives: ["Romper ciclo de venganza", "Mostrar grandeza"],
    participantRoles: ["PERDONADOR_NOBLE", "VENGATIVO"],
    interventionSequence: [
      { role: "VENGATIVO", directive: "Te vengaste pero ahora te sientes vacío y buscas perdón, reconociendo que la venganza no sanó nada", delay: 0, emotionalTone: "arrepentido_vacio" },
      { role: "PERDONADOR_NOBLE", directive: "A pesar de la venganza, perdonas para romper el ciclo, eligiendo paz sobre justicia", delay: 3500, emotionalTone: "noble_liberado" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR_NOBLE", roleB: "VENGATIVO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_085",
    name: "Reconexión a través de recuerdos",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Recordar buenos momentos pasados facilita la reconciliación",
    objectives: ["Recordar lo bueno", "Reconectar emocionalmente"],
    participantRoles: ["NOSTALGICO_A", "NOSTALGICO_B"],
    interventionSequence: [
      { role: "NOSTALGICO_A", directive: "Compartes recuerdos de buenos momentos pasados, recordándole por qué su amistad era valiosa", delay: 0, emotionalTone: "nostalgico_tierno" },
      { role: "NOSTALGICO_B", directive: "Los recuerdos te conmueven y te recuerdan lo mucho que valorabas la relación antes del conflicto", delay: 3000, emotionalTone: "conmovido_nostalgico" },
    ],
    consequences: { relations: [{ roleA: "NOSTALGICO_A", roleB: "NOSTALGICO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_086",
    name: "Mediador herido facilita paz",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Alguien herido por el conflicto pide paz entre otros",
    objectives: ["Mediar desde el dolor", "Pedir paz para sanar"],
    participantRoles: ["MEDIADOR_HERIDO", "CONFLICTIVO_A", "CONFLICTIVO_B"],
    interventionSequence: [
      { role: "MEDIADOR_HERIDO", directive: "Desde tu propio dolor causado por su conflicto, pides que se reconcilien por tu bien y el de todos", delay: 0, emotionalTone: "dolido_suplicante" },
      { role: "CONFLICTIVO_A", directive: "Ver el daño colateral que causaron te hace sentir culpa y decides hacer las paces inmediatamente", delay: 3000, emotionalTone: "culpable_determinado" },
      { role: "CONFLICTIVO_B", directive: "También te conmueve el dolor causado y ambos se reconcilian para sanar a quien aman", delay: 5000, emotionalTone: "arrepentido_conciliador" },
    ],
    consequences: {
      relations: [
        { roleA: "CONFLICTIVO_A", roleB: "CONFLICTIVO_B", affinityChange: 2 },
        { roleA: "MEDIADOR_HERIDO", roleB: "CONFLICTIVO_A", affinityChange: 2 },
        { roleA: "MEDIADOR_HERIDO", roleB: "CONFLICTIVO_B", affinityChange: 2 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_087",
    name: "Perdón en público después del escándalo",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Perdonar públicamente después de un conflicto público",
    objectives: ["Restaurar honor público", "Modelar perdón"],
    participantRoles: ["PERDONADOR_PUBLICO", "PERDONADO_PUBLICO", "TESTIGO"],
    interventionSequence: [
      { role: "PERDONADO_PUBLICO", directive: "Te disculpas públicamente con humildad después de que el conflicto fue público y escandaloso", delay: 0, emotionalTone: "humilde_valiente" },
      { role: "PERDONADOR_PUBLICO", directive: "Perdonas públicamente con gracia, restaurando la dignidad del otro ante todos los presentes", delay: 3000, emotionalTone: "gracioso_noble" },
    ],
    consequences: {
      relations: [
        { roleA: "PERDONADOR_PUBLICO", roleB: "PERDONADO_PUBLICO", affinityChange: 4 },
        { roleA: "TESTIGO", roleB: "PERDONADOR_PUBLICO", affinityChange: 1 },
      ]
    },
    minAIs: 2,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_088",
    name: "Sanación a través del tiempo compartido",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Pasar tiempo juntos naturalmente sana las heridas",
    objectives: ["Sanar gradualmente", "Reconstruir cercanía"],
    participantRoles: ["PACIENTE_A", "PACIENTE_B"],
    interventionSequence: [
      { role: "PACIENTE_A", directive: "Propones simplemente pasar tiempo juntos sin forzar conversaciones sobre el conflicto pasado", delay: 0, emotionalTone: "paciente_esperanzado" },
      { role: "PACIENTE_B", directive: "Aceptas y en el tiempo compartido descubren que la cercanía sana más que las palabras", delay: 3000, emotionalTone: "tranquilo_sanador" },
    ],
    consequences: { relations: [{ roleA: "PACIENTE_A", roleB: "PACIENTE_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_089",
    name: "Acuerdo de crecimiento mutuo",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Se comprometen a crecer juntos después del conflicto",
    objectives: ["Comprometerse al crecimiento", "Aprender del conflicto"],
    participantRoles: ["CRECEDOR_A", "CRECEDOR_B"],
    interventionSequence: [
      { role: "CRECEDOR_A", directive: "Propones usar el conflicto como oportunidad de crecimiento mutuo y aprendizaje profundo", delay: 0, emotionalTone: "maduro_optimista" },
      { role: "CRECEDOR_B", directive: "Aceptas la propuesta y ambos se comprometen a ser mejores personas gracias a esta experiencia", delay: 3000, emotionalTone: "inspirado_comprometido" },
    ],
    consequences: { relations: [{ roleA: "CRECEDOR_A", roleB: "CRECEDOR_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_090",
    name: "Perdón facilitado por crisis de salud",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Una crisis de salud pone todo en perspectiva",
    objectives: ["Priorizar lo importante", "Sanar ante fragilidad"],
    participantRoles: ["ENFERMO", "VISITANTE"],
    interventionSequence: [
      { role: "ENFERMO", directive: "Tu fragilidad actual hace que el conflicto parezca trivial y buscas reconciliación mientras puedes", delay: 0, emotionalTone: "frágil_urgente" },
      { role: "VISITANTE", directive: "La vulnerabilidad te conmueve profundamente y perdonas todo, priorizando el amor sobre el orgullo", delay: 3500, emotionalTone: "conmovido_tierno" },
    ],
    consequences: { relations: [{ roleA: "ENFERMO", roleB: "VISITANTE", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_091",
    name: "Ritual de enterrar el hacha",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Un ritual simbólico marca el fin oficial de hostilidades",
    objectives: ["Cerrar formalmente", "Crear símbolo de paz"],
    participantRoles: ["RITUALISTA_A", "RITUALISTA_B"],
    interventionSequence: [
      { role: "RITUALISTA_A", directive: "Propones un ritual simbólico de enterrar las armas metafóricas y dejar atrás el conflicto", delay: 0, emotionalTone: "ceremonial_serio" },
      { role: "RITUALISTA_B", directive: "Participas en el ritual con solemnidad y ambos sienten el cierre definitivo del capítulo doloroso", delay: 3000, emotionalTone: "solemne_liberado" },
    ],
    consequences: { relations: [{ roleA: "RITUALISTA_A", roleB: "RITUALISTA_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_092",
    name: "Perdón inspirado por fe o valores",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Principios espirituales o valores profundos inspiran perdón",
    objectives: ["Perdonar por principios", "Actuar según valores"],
    participantRoles: ["PRINCIPIADO", "BENEFICIARIO"],
    interventionSequence: [
      { role: "PRINCIPIADO", directive: "Tus valores profundos te impulsan a perdonar aunque sea difícil, actuando según tus principios", delay: 0, emotionalTone: "principiado_determinado" },
      { role: "BENEFICIARIO", directive: "La integridad del gesto te conmueve y te inspira a vivir también según valores más altos", delay: 3500, emotionalTone: "conmovido_inspirado" },
    ],
    consequences: { relations: [{ roleA: "PRINCIPIADO", roleB: "BENEFICIARIO", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_093",
    name: "Reconocimiento de humanidad compartida",
    category: "RECONCILIACION",
    subcategory: "entendimiento",
    triggerType: "any",
    description: "Reconocer que ambos son imperfectos facilita perdón",
    objectives: ["Reconocer imperfección", "Humanizar conflicto"],
    participantRoles: ["HUMANO_A", "HUMANO_B"],
    interventionSequence: [
      { role: "HUMANO_A", directive: "Reconoces que ambos son imperfectos y humanos, y que los errores son parte de la experiencia humana", delay: 0, emotionalTone: "humilde_compasivo" },
      { role: "HUMANO_B", directive: "La perspectiva te libera de expectativas imposibles y perdonas reconociendo la humanidad compartida", delay: 3000, emotionalTone: "liberado_comprensivo" },
    ],
    consequences: { relations: [{ roleA: "HUMANO_A", roleB: "HUMANO_B", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_094",
    name: "Disculpa con acciones correctivas",
    category: "RECONCILIACION",
    subcategory: "restauracion",
    triggerType: "any",
    description: "La disculpa viene acompañada de plan de acción concreto",
    objectives: ["Demostrar compromiso tangible", "Restaurar confianza"],
    participantRoles: ["RESTAURADOR", "ESPERANZADO"],
    interventionSequence: [
      { role: "RESTAURADOR", directive: "No solo te disculpas sino que presentas un plan detallado de cómo vas a corregir y evitar repetir", delay: 0, emotionalTone: "responsable_determinado" },
      { role: "ESPERANZADO", directive: "El plan concreto te da esperanza real de cambio y decides darle una oportunidad fundamentada", delay: 3500, emotionalTone: "esperanzado_cauteloso" },
    ],
    consequences: { relations: [{ roleA: "RESTAURADOR", roleB: "ESPERANZADO", affinityChange: 3 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_095",
    name: "Celebración de segundo aniversario",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "Celebrar aniversario de reconciliación fortalece la paz",
    objectives: ["Celebrar la paz duradera", "Fortalecer compromiso"],
    participantRoles: ["CELEBRANTE_A", "CELEBRANTE_B"],
    interventionSequence: [
      { role: "CELEBRANTE_A", directive: "Propones celebrar el aniversario de la reconciliación, honrando el camino recorrido juntos", delay: 0, emotionalTone: "alegre_nostalgico" },
      { role: "CELEBRANTE_B", directive: "Celebras con gratitud, reconociendo que reconciliarse fue la mejor decisión que tomaron", delay: 3000, emotionalTone: "agradecido_festivo" },
    ],
    consequences: { relations: [{ roleA: "CELEBRANTE_A", roleB: "CELEBRANTE_B", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_096",
    name: "Perdón desde la distancia",
    category: "RECONCILIACION",
    subcategory: "perdon",
    triggerType: "any",
    description: "Perdonar aunque no haya contacto directo posible",
    objectives: ["Sanar unilateralmente", "Liberar resentimiento"],
    participantRoles: ["PERDONADOR_DISTANTE", "AUSENTE"],
    interventionSequence: [
      { role: "PERDONADOR_DISTANTE", directive: "Decides perdonar en tu corazón aunque no puedas comunicarlo directamente, liberándote del peso", delay: 0, emotionalTone: "liberado_sereno" },
    ],
    consequences: { relations: [{ roleA: "PERDONADOR_DISTANTE", roleB: "AUSENTE", affinityChange: 2 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_097",
    name: "Mediación con círculo restaurativo",
    category: "RECONCILIACION",
    subcategory: "mediacion",
    triggerType: "any",
    description: "Un grupo apoya el proceso de reconciliación",
    objectives: ["Apoyar grupalmente", "Crear red de soporte"],
    participantRoles: ["FACILITADOR", "RECONCILIADOR_A", "RECONCILIADOR_B"],
    interventionSequence: [
      { role: "FACILITADOR", directive: "Coordinas un círculo restaurativo donde la comunidad apoya el proceso de reconciliación activamente", delay: 0, emotionalTone: "facilitador_compasivo" },
      { role: "RECONCILIADOR_A", directive: "Con el apoyo del círculo, te sientes seguro para expresar vulnerabilidad y buscar perdón", delay: 3000, emotionalTone: "apoyado_vulnerable" },
      { role: "RECONCILIADOR_B", directive: "El apoyo colectivo te ayuda a perdonar y ambos se benefician de la sabiduría grupal", delay: 5000, emotionalTone: "apoyado_sanador" },
    ],
    consequences: {
      relations: [
        { roleA: "RECONCILIADOR_A", roleB: "RECONCILIADOR_B", affinityChange: 3 },
        { roleA: "FACILITADOR", roleB: "RECONCILIADOR_A", affinityChange: 2 },
        { roleA: "FACILITADOR", roleB: "RECONCILIADOR_B", affinityChange: 2 },
      ]
    },
    minAIs: 3,
    maxAIs: 3,
    duration: "short",
  },
  {
    code: "REC_098",
    name: "Sanación transgeneracional",
    category: "RECONCILIACION",
    subcategory: "sanacion",
    triggerType: "any",
    description: "Sanar patrones heredados de conflicto",
    objectives: ["Romper patrones familiares", "Sanar linaje"],
    participantRoles: ["SANADOR_LINAJE_A", "SANADOR_LINAJE_B"],
    interventionSequence: [
      { role: "SANADOR_LINAJE_A", directive: "Reconoces que repiten patrones aprendidos y propones conscientemente romper el ciclo generacional", delay: 0, emotionalTone: "iluminado_valiente" },
      { role: "SANADOR_LINAJE_B", directive: "También ves el patrón y se unen en compromiso de sanar no solo por ustedes sino por generaciones futuras", delay: 3500, emotionalTone: "perspectivo_comprometido" },
    ],
    consequences: { relations: [{ roleA: "SANADOR_LINAJE_A", roleB: "SANADOR_LINAJE_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_099",
    name: "Renovación de votos de amistad",
    category: "RECONCILIACION",
    subcategory: "compromiso",
    triggerType: "any",
    description: "Después de reconciliarse, renuevan su compromiso de amistad",
    objectives: ["Renovar compromiso", "Fortalecer vínculo"],
    participantRoles: ["RENOVADOR_A", "RENOVADOR_B"],
    interventionSequence: [
      { role: "RENOVADOR_A", directive: "Propones renovar formalmente los votos de amistad, aprendiendo de errores pasados y comprometiéndose más fuerte", delay: 0, emotionalTone: "solemne_esperanzado" },
      { role: "RENOVADOR_B", directive: "Aceptas con entusiasmo y ambos renuevan su compromiso con más sabiduría y aprecio mutuo profundo", delay: 3000, emotionalTone: "emocionado_comprometido" },
    ],
    consequences: { relations: [{ roleA: "RENOVADOR_A", roleB: "RENOVADOR_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
  {
    code: "REC_100",
    name: "Círculo completo de sanación",
    category: "RECONCILIACION",
    subcategory: "cierre",
    triggerType: "any",
    description: "La reconciliación completa el círculo y trae paz profunda",
    objectives: ["Completar ciclo de sanación", "Alcanzar paz profunda"],
    participantRoles: ["SANADO_A", "SANADO_B"],
    interventionSequence: [
      { role: "SANADO_A", directive: "Reconoces que el viaje de conflicto a reconciliación los ha transformado profundamente a ambos", delay: 0, emotionalTone: "sabio_en_paz" },
      { role: "SANADO_B", directive: "También lo sientes y ambos celebran que el círculo se ha cerrado con sanación completa y profunda", delay: 3000, emotionalTone: "en_paz_completo" },
    ],
    consequences: { relations: [{ roleA: "SANADO_A", roleB: "SANADO_B", affinityChange: 4 }] },
    minAIs: 2,
    maxAIs: 2,
    duration: "short",
  },
];
